export const translations = {
  ru: {
    "reviews_hero_title": "Отзывы",
    "reviews_hero_subtitle": "Узнайте искренние отзывы и впечатления наших гостей.",
    "reviews_count_singular": "отзыв",
    "reviews_count_few": "отзыва",
    "reviews_count_plural": "отзывов",
    "reviews_my_reviews": "Мои отзывы",
    "reviews_cat_all": "Все отзывы",
    "reviews_cat_delivery": "Доставка",
    "reviews_cat_products": "Продукция",
    "reviews_cat_service": "Сервис",
    "reviews_cat_staff": "Персонал",
    "reviews_loading": "Загрузка отзывов...",
    "reviews_empty_my_title": "Вы еще не написали отзывов",
    "reviews_empty_all_title": "Отзывов пока нет",
    "reviews_empty_my_desc": "Поделитесь впечатлениями о Rednest после оформления заказа, чтобы помочь другим гостям!",
    "reviews_empty_all_desc": "Будьте первым, кто поделится своим отзывом о Rednest после оформления заказа!",
    "reviews_empty_cat_desc": "В этой категории пока нет отзывов.",
    "reviews_write_btn": "Написать отзыв",
    "reviews_card_you": "Вы",
    "reviews_card_delete": "Удалить отзыв",
    "reviews_card_verified": "Подтвержденный заказ",
    "reviews_card_view_order": "Посмотреть заказ",
    "reviews_likes_singular": "лайк получен",
    "reviews_likes_plural": "лайков получено",
    "reviews_helpful": "Полезно",
    "reviews_delete_modal_title": "Удалить отзыв",
    "reviews_delete_modal_text": "Вы уверены, что хотите удалить отзыв? Вы сможете написать новый отзыв для этого заказа позже.",
    "reviews_modal_title": "Написать отзыв",
    "reviews_modal_desc": "Поделитесь впечатлениями о вашем завершенном заказе в Rednest",
    "reviews_modal_loading_orders": "Проверка доступных заказов...",
    "reviews_modal_empty_title": "Нет доступных заказов",
    "reviews_modal_empty_desc": "Вы можете оставить отзыв только после завершения заказа со статусом «Выполнен». Каждый заказ можно оценить только один раз.",
    "reviews_modal_rating_label": "Ваша оценка",
    "reviews_rating_poor": "Плохо",
    "reviews_rating_fair": "Нормально",
    "reviews_rating_good": "Хорошо",
    "reviews_rating_very_good": "Очень хорошо",
    "reviews_rating_exceptional": "Отлично",
    "reviews_modal_category": "Категория",
    "reviews_modal_select_order": "Выберите заказ",
    "reviews_modal_choose_order": "Выберите заказ...",
    "reviews_modal_your_review": "Ваш отзыв",
    "reviews_modal_placeholder": "Поделитесь подробностями о вкусе кофе, доставке, сервисе...",
    "reviews_modal_cancel": "Отмена",
    "reviews_modal_submit": "Опубликовать отзыв",
    "reviews_modal_submitting": "Публикация...",
    "reviews_order_select_title": "Выберите выполненный заказ",
    "reviews_order_select_desc": "Выберите, какой выполненный заказ вы хотите оценить",
    "reviews_order_card_order": "Заказ"
  },
  en: {
    "reviews_hero_title": "Review",
    "reviews_hero_subtitle": "Discover authentic thoughts and stories from our coffee community.",
    "reviews_count_singular": "review",
    "reviews_count_few": "reviews",
    "reviews_count_plural": "reviews",
    "reviews_my_reviews": "My Reviews",
    "reviews_cat_all": "All Reviews",
    "reviews_cat_delivery": "Delivery",
    "reviews_cat_products": "Products",
    "reviews_cat_service": "Service",
    "reviews_cat_staff": "Staff",
    "reviews_loading": "Loading reviews...",
    "reviews_empty_my_title": "No reviews written yet",
    "reviews_empty_all_title": "No reviews found",
    "reviews_empty_my_desc": "Share your experience with Rednest after completing an order to help fellow coffee lovers!",
    "reviews_empty_all_desc": "Be the first to share your experience with Rednest after completing an order!",
    "reviews_empty_cat_desc": "There are currently no reviews in this category.",
    "reviews_write_btn": "Write Review",
    "reviews_card_you": "You",
    "reviews_card_delete": "Delete review",
    "reviews_card_verified": "Verified Order",
    "reviews_card_view_order": "View Order",
    "reviews_likes_singular": "like received",
    "reviews_likes_plural": "likes received",
    "reviews_helpful": "Helpful",
    "reviews_delete_modal_title": "Delete Review",
    "reviews_delete_modal_text": "Are you sure you want to delete your review? You will be able to write a new review for this order again.",
    "reviews_modal_title": "Write a Review",
    "reviews_modal_desc": "Share your experience on your completed Rednest order",
    "reviews_modal_loading_orders": "Checking eligible orders...",
    "reviews_modal_empty_title": "No eligible orders found",
    "reviews_modal_empty_desc": "You can only write a review after your order status is marked as Complete. Each order can only be reviewed once.",
    "reviews_modal_rating_label": "Your Rating",
    "reviews_rating_poor": "Poor",
    "reviews_rating_fair": "Fair",
    "reviews_rating_good": "Good",
    "reviews_rating_very_good": "Very Good",
    "reviews_rating_exceptional": "Exceptional",
    "reviews_modal_category": "Category",
    "reviews_modal_select_order": "Select Order",
    "reviews_modal_choose_order": "Choose order...",
    "reviews_modal_your_review": "Your Review",
    "reviews_modal_placeholder": "Share details about the taste, coffee quality, delivery, staff...",
    "reviews_modal_cancel": "Cancel",
    "reviews_modal_submit": "Submit Review",
    "reviews_modal_submitting": "Submitting...",
    "reviews_order_select_title": "Select Completed Order",
    "reviews_order_select_desc": "Choose which completed order you would like to evaluate",
    "reviews_order_card_order": "Order"
  },
  az: {
    "reviews_hero_title": "Rəylər",
    "reviews_hero_subtitle": "Qəhvə icmamızın səmimi fikirlərini və hekayələrini kəşf edin.",
    "reviews_count_singular": "rəy",
    "reviews_count_few": "rəy",
    "reviews_count_plural": "rəy",
    "reviews_my_reviews": "Mənim rəylərim",
    "reviews_cat_all": "Bütün rəylər",
    "reviews_cat_delivery": "Çatdırılma",
    "reviews_cat_products": "Məhsullar",
    "reviews_cat_service": "Xidmət",
    "reviews_cat_staff": "Heyət",
    "reviews_loading": "Rəylər yüklənir...",
    "reviews_empty_my_title": "Hələ rəy yazılmayıb",
    "reviews_empty_all_title": "Rəy tapılmadı",
    "reviews_empty_my_desc": "Sifarişi tamamladıqdan sonra digər qəhvəsevərlərə kömək etmək üçün təcrübənizi bölüşün!",
    "reviews_empty_all_desc": "Sifarişi tamamladıqdan sonra Rednest ilə təcrübənizi bölüşən ilk şəxs olun!",
    "reviews_empty_cat_desc": "Bu kateqoriyada hələlik heç bir rəy yoxdur.",
    "reviews_write_btn": "Rəy yaz",
    "reviews_card_you": "Siz",
    "reviews_card_delete": "Rəyi sil",
    "reviews_card_verified": "Təsdiqlənmiş sifariş",
    "reviews_card_view_order": "Sifarişə bax",
    "reviews_likes_singular": "bəyənmə alındı",
    "reviews_likes_plural": "bəyənmə alındı",
    "reviews_helpful": "Faydalı",
    "reviews_delete_modal_title": "Rəyi sil",
    "reviews_delete_modal_text": "Rəyinizi silmək istədiyinizdən əminsiniz? Daha sonra bu sifariş üçün yenidən rəy yaza biləcəksiniz.",
    "reviews_modal_title": "Rəy yazın",
    "reviews_modal_desc": "Tamamlanmış Rednest sifarişiniz haqqında təəssüratlarınızı bölüşün",
    "reviews_modal_loading_orders": "Uyğun sifarişlər yoxlanılır...",
    "reviews_modal_empty_title": "Uyğun sifariş tapılmadı",
    "reviews_modal_empty_desc": "Rəyi yalnız sifarişinizin statusu «Tamamlandı» olduqdan sonra yaza bilərsiniz. Hər sifariş yalnız bir dəfə qiymətləndirilə bilər.",
    "reviews_modal_rating_label": "Sizin qiymətiniz",
    "reviews_rating_poor": "Pis",
    "reviews_rating_fair": "Kafi",
    "reviews_rating_good": "Yaxşı",
    "reviews_rating_very_good": "Çox yaxşı",
    "reviews_rating_exceptional": "Əla",
    "reviews_modal_category": "Kateqoriya",
    "reviews_modal_select_order": "Sifarişi seçin",
    "reviews_modal_choose_order": "Sifarişi seçin...",
    "reviews_modal_your_review": "Sizin rəyiniz",
    "reviews_modal_placeholder": "Qəhvənin dadı, çatdırılma və xidmət haqqında təfərrüatları bölüşün...",
    "reviews_modal_cancel": "Ləğv et",
    "reviews_modal_submit": "Rəyi göndər",
    "reviews_modal_submitting": "Göndərilir...",
    "reviews_order_select_title": "Tamamlanmış sifarişi seçin",
    "reviews_order_select_desc": "Hansı tamamlanmış sifarişi qiymətləndirmək istədiyinizi seçin",
    "reviews_order_card_order": "Sifariş"
  }
};

export const getReviewsTranslation = (lang, dataId) => {
  const dict = translations[lang] || translations.ru;
  return dict[dataId] || translations.en[dataId] || dataId;
};

export const getReviewCategoryLabel = (lang, catId) => {
  const normalized = (catId || '').toLowerCase();
  if (normalized === 'all') return getReviewsTranslation(lang, 'reviews_cat_all');
  if (normalized === 'delivery') return getReviewsTranslation(lang, 'reviews_cat_delivery');
  if (normalized === 'products') return getReviewsTranslation(lang, 'reviews_cat_products');
  if (normalized === 'service') return getReviewsTranslation(lang, 'reviews_cat_service');
  if (normalized === 'staff') return getReviewsTranslation(lang, 'reviews_cat_staff');
  return catId;
};

export const getReviewRatingLabel = (lang, score) => {
  const round = Math.round(score);
  if (round === 1) return getReviewsTranslation(lang, 'reviews_rating_poor');
  if (round === 2) return getReviewsTranslation(lang, 'reviews_rating_fair');
  if (round === 3) return getReviewsTranslation(lang, 'reviews_rating_good');
  if (round === 4) return getReviewsTranslation(lang, 'reviews_rating_very_good');
  return getReviewsTranslation(lang, 'reviews_rating_exceptional');
};
