export const translations = {
  ru: {
    "pm_hero_title": "Способы оплаты",
    "pm_hero_desc": "Управление сохраненными картами Visa и Mastercard, настройка основного метода оплаты для быстрых покупок",
    "pm_btn_add": "Добавить новую карту",
    "pm_limit_reached": "Вы можете сохранить максимум 3 банковские карты. Пожалуйста, удалите существующую карту, чтобы добавить новую.",
    "pm_limit_title": "Ошибка карты",
    "pm_loading": "Загрузка способов оплаты...",
    "pm_error_load": "Не удалось загрузить сохраненные способы оплаты.",
    "pm_try_again": "Попробовать снова",
    "pm_added_on": "Добавлена",
    "pm_badge_default": "Основная",
    "pm_cardholder": "Владелец",
    "pm_expires": "Срок",
    "pm_set_default": "Сделать основной",
    "pm_setting_default": "Сохранение...",
    "pm_delete": "Удалить",
    "pm_toast_added": "Банковская карта успешно добавлена!",
    "pm_toast_default": "установлена как основная карта!",
    "pm_toast_deleted": "Банковская карта успешно удалена.",
    "pm_this_card": "эта карта",
    "pm_ending_in": "с окончанием на",

    "card_modal_title": "Добавить банковскую карту",
    "card_modal_subtitle": "Введите данные вашей карты Visa или Mastercard",
    "card_number": "Номер карты",
    "card_expiry": "Срок действия",
    "card_cvc": "CVC / CVV",
    "card_holder_label": "Имя владельца (необязательно)",
    "card_holder_ph": "например: ELCHIN",
    "card_name_label": "Название карты (необязательно)",
    "card_name_ph": "например: Зарплатная карта",
    "card_set_default": "Сделать основной",
    "card_agree_prefix": "Согласен с ",
    "card_agree_rules": "Правилами оплаты",
    "card_btn_cancel": "Отмена",
    "card_btn_add": "Добавить карту",
    "card_btn_saving": "Сохранение карты...",
    "card_err_num_req": "Номер карты обязателен.",
    "card_err_num_len": "Номер карты должен содержать 16 цифр.",
    "card_err_brand": "Поддерживаются только карты Visa и Mastercard.",
    "card_err_luhn": "Неверная контрольная сумма номера карты.",
    "card_err_exp_req": "Срок действия обязателен.",
    "card_err_exp_fmt": "Формат должен быть ММ/ГГ.",
    "card_err_exp_month": "Месяц должен быть от 01 до 12.",
    "card_err_exp_past": "Срок действия карты истек.",
    "card_err_cvc_req": "CVC обязателен.",
    "card_err_cvc_len": "Должно быть 3 цифры.",
    "card_err_holder": "Пожалуйста, введите корректное имя владельца.",
    "card_err_rules": "Необходимо согласиться с правилами оплаты.",
    "modal_understand": "Понятно"
  },
  en: {
    "pm_hero_title": "Payment Methods",
    "pm_hero_desc": "Manage your saved Visa and Mastercard cards, configure default payment method, and speed up checkout",
    "pm_btn_add": "Add New Card",
    "pm_limit_reached": "You can only save up to 3 payment cards. Please delete an existing card to add a new one.",
    "pm_limit_title": "Card Error",
    "pm_loading": "Loading your saved payment methods...",
    "pm_error_load": "Failed to load saved payment methods.",
    "pm_try_again": "Try Again",
    "pm_added_on": "Added",
    "pm_badge_default": "Default",
    "pm_cardholder": "Cardholder",
    "pm_expires": "Expires",
    "pm_set_default": "Set Default",
    "pm_setting_default": "Setting...",
    "pm_delete": "Delete",
    "pm_toast_added": "Payment card added successfully!",
    "pm_toast_default": "set as default payment method!",
    "pm_toast_deleted": "Payment card removed successfully.",
    "pm_this_card": "this card",
    "pm_ending_in": "ending in",

    "card_modal_title": "Add Payment Card",
    "card_modal_subtitle": "Enter your Visa or Mastercard details",
    "card_number": "Card Number",
    "card_expiry": "Expiry Date",
    "card_cvc": "CVC / CVV",
    "card_holder_label": "Cardholder (Optional)",
    "card_holder_ph": "e.g. ELCHIN",
    "card_name_label": "Card Label (Optional)",
    "card_name_ph": "e.g. Salary Card",
    "card_set_default": "Set as default",
    "card_agree_prefix": "Agree to ",
    "card_agree_rules": "Payment Rules",
    "card_btn_cancel": "Cancel",
    "card_btn_add": "Add Card",
    "card_btn_saving": "Saving Card...",
    "card_err_num_req": "Card number is required.",
    "card_err_num_len": "Card number must be 16 digits.",
    "card_err_brand": "Only Visa and Mastercard cards are supported.",
    "card_err_luhn": "Invalid card number checksum.",
    "card_err_exp_req": "Expiry date is required.",
    "card_err_exp_fmt": "Format must be MM/YY.",
    "card_err_exp_month": "Month must be 01–12.",
    "card_err_exp_past": "Card has expired.",
    "card_err_cvc_req": "CVC is required.",
    "card_err_cvc_len": "Must be 3 digits.",
    "card_err_holder": "Please enter a valid cardholder name.",
    "card_err_rules": "You must agree to the payment rules.",
    "modal_understand": "Understand"
  },
  az: {
    "pm_hero_title": "Ödəniş üsulları",
    "pm_hero_desc": "Saxlanılan Visa və Mastercard kartlarınızı idarə edin, əsas ödəniş üsulunu seçin və sürətli sifariş verin",
    "pm_btn_add": "Yeni kart əlavə et",
    "pm_limit_reached": "Maksimum 3 bank kartı saxlaya bilərsiniz. Yenisini əlavə etmək üçün mövcud kartı silin.",
    "pm_limit_title": "Kart xətası",
    "pm_loading": "Yadda saxlanılmış ödəniş üsulları yüklənir...",
    "pm_error_load": "Yadda saxlanılmış ödəniş üsullarını yükləmək mümkün olmadı.",
    "pm_try_again": "Yenidən cəhd edin",
    "pm_added_on": "Əlavə edilib",
    "pm_badge_default": "Əsas",
    "pm_cardholder": "Kart sahibi",
    "pm_expires": "Bitmə vaxtı",
    "pm_set_default": "Əsas et",
    "pm_setting_default": "Dəyişdirilir...",
    "pm_delete": "Sil",
    "pm_toast_added": "Ödəniş kartı uğurla əlavə edildi!",
    "pm_toast_default": "əsas ödəniş üsulu kimi təyin edildi!",
    "pm_toast_deleted": "Ödəniş kartı uğurla silindi.",
    "pm_this_card": "bu kart",
    "pm_ending_in": "son rəqəmləri",

    "card_modal_title": "Ödəniş kartı əlavə et",
    "card_modal_subtitle": "Visa və ya Mastercard kart məlumatlarınızı daxil edin",
    "card_number": "Kart nömrəsi",
    "card_expiry": "Bitmə tarixi",
    "card_cvc": "CVC / CVV",
    "card_holder_label": "Kart sahibi (istəyə görə)",
    "card_holder_ph": "məs: ELCHIN",
    "card_name_label": "Kartın adı (istəyə görə)",
    "card_name_ph": "məs: Maaş kartı",
    "card_set_default": "Əsas kart et",
    "card_agree_prefix": "Razıyam: ",
    "card_agree_rules": "Ödəniş qaydaları",
    "card_btn_cancel": "Ləğv et",
    "card_btn_add": "Kart əlavə et",
    "card_btn_saving": "Kart saxlanılır...",
    "card_err_num_req": "Kart nömrəsi mütləqdir.",
    "card_err_num_len": "Kart nömrəsi 16 rəqəmdən ibarət olmalıdır.",
    "card_err_brand": "Yalnız Visa və Mastercard kartları dəstəklənir.",
    "card_err_luhn": "Kart nömrəsinin yoxlama cəmi yanlışdır.",
    "card_err_exp_req": "Bitmə tarixi mütləqdir.",
    "card_err_exp_fmt": "Format AA/İİ olmalıdır.",
    "card_err_exp_month": "Ay 01–12 aralığında olmalıdır.",
    "card_err_exp_past": "Kartın etibarlılıq müddəti bitib.",
    "card_err_cvc_req": "CVC mütləqdir.",
    "card_err_cvc_len": "3 rəqəm olmalıdır.",
    "card_err_holder": "Zəhmət olmasa kart sahibinin düzgün adını qeyd edin.",
    "card_err_rules": "Ödəniş qaydaları ilə razılaşmaq mütləqdir.",
    "modal_understand": "Aydındır"
  }
};

export const getPaymentMethodsTranslation = (lang, dataId) => {
  const dict = translations[lang] || translations.az || translations.ru;
  return dict[dataId] || (translations.en && translations.en[dataId]) || dataId;
};
