export const translations = {
  az: {
    stepBadge: 'Sifariş & Ödəniş',
    heroTitle: 'Ödəniş üsulunu seçin',
    heroDesc: 'Sifarişiniz üçün necə ödəmək istədiyinizi seçin.',
    emptyBasket: 'Səbətiniz boşdur. Sifariş vermək üçün menyudan məhsullar əlavə edin.',
    browseMenu: 'Menyuya bax',
    inStoreBadge: 'Məkanda təhvil',
    payAtCashier: 'Kassada ödəniş',
    payAtCashierCounter: 'Kassa piştaxtasında ödəniş',
    cashierDesc: 'Təzə hazırlanmış sifarişinizi barista piştaxtasından götürərkən nağd və ya kartla ödəyin.',
    cashPayment: 'Nağd ödəniş',
    cardNfc: 'Kart və NFC',
    usePromoCodes: 'Promokodlardan istifadə',
    selectedBadge: '✓ Seçildi',
    chooseCashier: 'Kassanı seçin',
    instantBadge: 'Sürətli və Təmassız',
    payOnline: 'Onlayn ödəniş',
    payOnlineInstantly: 'Dərhal onlayn ödəyin',
    onlineDesc: 'Sifarişinizin dərhal hazırlanması üçün bank kartınız və ya Rednest balansınızla təhlükəsiz ödəyin.',
    visaMastercard: 'Visa və ya Mastercard',
    payViaBalance: 'Balansla ödəniş',
    payViaStripe: 'Stripe ilə ödəniş',
    googlePay: 'Google Pay',
    earnCashback: 'Keşbek qazanın',
    chooseOnline: 'Onlaynı seçin',
    selectedPayment: 'Seçilmiş ödəniş:',
    cashierStepDesc: 'Sifarişiniz baristalara göndəriləcək və təhvil alarkən məkanda ödənilmək üçün qeyd ediləcək.',
    onlineStepDesc: 'Sifarişin dərhal təsdiqlənməsi üçün təhlükəsiz onlayn ödənişə keçilir.',
    changeMethod: 'Üsulu dəyiş',
    selectPromo: 'Tətbiq olunacaq promokodu seçin:',
    promosAvailable: '{count} ədəd mövcuddur',
    dontUsePromo: 'Heç bir promokod istifadə etmə',
    itemsCount: 'Məhsullar:',
    itemsSuffix: 'məhsul',
    discountLabel: 'Endirim:',
    totalToPay: 'Ödəniləcək yekun:',
    confirmOrder: 'Sifarişi təsdiqlə və rəsmiləşdir',
    continueOnline: 'Onlayn ödənişə keç',
    placingOrder: 'Sifariş rəsmiləşdirilir...',
    backToBasket: 'Səbətə qayıt',
    orderFailed: 'Sifarişi rəsmiləşdirmək mümkün olmadı. Zəhmət olmasa yenidən cəhd edin.',
    orderNetworkError: 'Sifariş zamanı xəta baş verdi. Zəhmət olmasa internet bağlantınızı yoxlayın.',
    onlineModalTitle: 'Onlayn Ödəniş Xidməti',
    onlineModalDesc: 'Ödəniş üsulunu seçin',
    cancel: 'Ləğv et',
    payWithBalance: 'Balansla ödə',
    continueToPayment: 'Ödənişə davam et',
    popularBadge: 'Məşhur',
    instantSpeedBadge: 'Dərhal',
    cardsBadge: 'Kartlar',
    oneTapBadge: '1 Toxunuşla',
    balancePrefix: 'Balans:',
    serviceStripeTitle: 'Stripe ilə ödəniş',
    serviceStripeDesc: 'Sürətli və təhlükəsiz beynəlxalq ödəniş',
    serviceBalanceTitle: 'Rednest Balansı',
    serviceBalanceDesc: 'Hesab balansınızdan dərhal ödəniş',
    serviceCardsTitle: 'Visa və ya Mastercard',
    serviceCardsDesc: 'Debet və ya kredit kartı ilə ödəniş',
    serviceGPayTitle: 'Google Pay',
    serviceGPayDesc: 'Google Pay ilə bir toxunuşla ödəniş',
    orderSuccessTitle: 'Sifariş Uğurla Rəsmiləşdirildi!',
    orderSuccessDesc: 'Sifariş baristaya göndərildi. Piştaxtada sifariş nömrənizi təqdim edin.',
    orderNumberLabel: 'Sifariş Nömrəsi',
    mentionAtCounter: 'Bunu piştaxtada bildirin',
    promoDiscount: 'Promokod endirimi',
    cashbackAdded: 'Keşbek əlavə olundu',
    paymentMethodLabel: 'Ödəniş üsulu',
    backToMenu: 'Menyuya qayıt',
    viewOrders: 'Sifarişlərə bax',
    statusPaidOnline: 'Onlayn ödənilib',
    statusPendingPayment: 'Ödəniş gözlənilir',
    methodStripe: 'Stripe',
    methodBalance: 'Rednest Hesab Balansı',
    methodCards: 'Visa / Mastercard',
    methodGPay: 'Google Pay',
    methodCashierCard: 'Kassada ödəniş (Kart / NFC)',
    methodCashierCash: 'Kassada ödəniş',
    stripeModalTitle: 'Kart və Onlayn Ödəniş',
    stripeAmountToPay: 'Ödəniləcək məbləğ:',
    loadingOptions: 'Ödəniş seçimləri yüklənir...',
    selectSavedCard: 'Yadda saxlanılmış kartı seçin',
    useNewCard: 'Yeni kartdan istifadə et',
    chooseFromSaved: 'Yadda saxlanılmış kartlardan seç',
    defaultBadge: 'ƏSAS',
    payAmount: 'Ödə {amount} ₼',
    processing: 'İcra olunur...',
    cardNumberLabel: 'Kart Nömrəsi',
    expiryDateLabel: 'Bitmə Tarixi',
    cvcLabel: 'CVC / CVV',
    cardholderLabel: 'Kart Sahibi (İxtiyari)',
    cardLabelLabel: 'Kartın Adı (İxtiyari)',
    cardholderPlaceholder: 'məs. ELCHIN',
    cardLabelPlaceholder: 'məs. Maaş Kartı',
    saveCardCheckbox: 'Kartı gələcək ödənişlər üçün yadda saxla',
    agreeToRules: 'Razıyam: ',
    paymentRulesLink: 'Ödəniş Qaydaları',
    paymentErrorTitle: 'Ödəniş Xətası',
    errCardNumberRequired: 'Kart nömrəsi tələb olunur.',
    errCardNumberDigits: 'Kart nömrəsi 16 rəqəmdən ibarət olmalıdır.',
    errCardNumberInvalid: 'Yanlış kart nömrəsi.',
    errCardBrandUnsupported: 'Yalnız Visa və Mastercard qəbul edilir.',
    errExpiryRequired: 'Bitmə tarixi tələb olunur.',
    errExpiryFormat: 'Format AA/İİ olmalıdır.',
    errExpiryMonth: 'Yanlış ay.',
    errCardExpired: 'Kartın vaxtı bitib.',
    errCvcRequired: 'CVC tələb olunur.',
    errCvcDigits: '3 rəqəm olmalıdır.',
    errCardholderInvalid: 'Zəhmət olmasa düzgün kart sahibi adı daxil edin.',
    errAgreedRequired: 'Ödəniş qaydaları ilə razılaşmalısınız.',
    errMaxCardsReached: 'Ən çox 3 kart yadda saxlaya bilərsiniz. Zəhmət olmasa "Yadda saxla" işarəsini silin və ya mövcud kartı silin.',
    errPaymentFailed: 'Ödəniş baş tutmadı. Zəhmət olmasa yenidən cəhd edin.',
    errPaymentCheckInfo: 'Ödəniş baş tutmadı. Zəhmət olmasa kart məlumatlarını yoxlayın.',
    errProcessingGeneral: 'Ödəniş icrası zamanı xəta baş verdi.',
  },
  ru: {
    stepBadge: 'Оформление & Оплата',
    heroTitle: 'Выберите способ оплаты',
    heroDesc: 'Выберите наиболее удобный способ оплаты вашего заказа.',
    emptyBasket: 'Ваша корзина пуста. Добавьте товары из меню, чтобы оформить заказ.',
    browseMenu: 'В меню',
    inStoreBadge: 'Самовывоз',
    payAtCashier: 'Оплата на кассе',
    payAtCashierCounter: 'Оплата у стойки кассы',
    cashierDesc: 'Оплатите наличными или банковской картой при получении свежеприготовленного заказа у бариста.',
    cashPayment: 'Оплата наличными',
    cardNfc: 'Карта и NFC',
    usePromoCodes: 'Использование промокодов',
    selectedBadge: '✓ Выбрано',
    chooseCashier: 'Выбрать кассу',
    instantBadge: 'Быстро и бесконтактно',
    payOnline: 'Оплатить онлайн',
    payOnlineInstantly: 'Мгновенная онлайн-оплата',
    onlineDesc: 'Безопасная оплата картой или с баланса Rednest для немедленного начала приготовления заказа.',
    visaMastercard: 'Visa или Mastercard',
    payViaBalance: 'Оплата с баланса',
    payViaStripe: 'Оплата через Stripe',
    googlePay: 'Google Pay',
    earnCashback: 'Получайте кешбэк',
    chooseOnline: 'Выбрать онлайн',
    selectedPayment: 'Выбранный способ:',
    cashierStepDesc: 'Ваш заказ будет отправлен бариста и отмечен для оплаты при получении в кофейне.',
    onlineStepDesc: 'Переход к безопасной онлайн-оплате для моментального подтверждения заказа.',
    changeMethod: 'Изменить',
    selectPromo: 'Выберите промокод:',
    promosAvailable: 'доступно: {count}',
    dontUsePromo: 'Не использовать промокод',
    itemsCount: 'Товары:',
    itemsSuffix: 'тов.',
    discountLabel: 'Скидка:',
    totalToPay: 'Итого к оплате:',
    confirmOrder: 'Подтвердить и заказать',
    continueOnline: 'Перейти к онлайн-оплате',
    placingOrder: 'Оформление заказа...',
    backToBasket: 'Назад в корзину',
    orderFailed: 'Не удалось оформить заказ. Пожалуйста, попробуйте снова.',
    orderNetworkError: 'Произошла ошибка при оформлении заказа. Проверьте интернет-соединение.',
    onlineModalTitle: 'Онлайн-сервис оплаты',
    onlineModalDesc: 'Выберите способ оплаты',
    cancel: 'Отмена',
    payWithBalance: 'Оплатить с баланса',
    continueToPayment: 'Продолжить к оплате',
    popularBadge: 'Популярно',
    instantSpeedBadge: 'Мгновенно',
    cardsBadge: 'Карты',
    oneTapBadge: 'В 1 клик',
    balancePrefix: 'Баланс:',
    serviceStripeTitle: 'Оплата через Stripe',
    serviceStripeDesc: 'Быстрая и безопасная международная оплата',
    serviceBalanceTitle: 'Баланс Rednest',
    serviceBalanceDesc: 'Моментальная оплата с вашего счета Rednest',
    serviceCardsTitle: 'Visa или Mastercard',
    serviceCardsDesc: 'Оплата дебетовой или кредитной картой',
    serviceGPayTitle: 'Google Pay',
    serviceGPayDesc: 'Оплата в одно касание через Google Pay',
    orderSuccessTitle: 'Заказ успешно оформлен!',
    orderSuccessDesc: 'Заказ отправлен бариста. Назовите номер заказа у стойки выдачи.',
    orderNumberLabel: 'Номер заказа',
    mentionAtCounter: 'Назовите этот номер на кассе',
    promoDiscount: 'Скидка по промокоду',
    cashbackAdded: 'Начислен кешбэк',
    paymentMethodLabel: 'Способ оплаты',
    backToMenu: 'В меню',
    viewOrders: 'Мои заказы',
    statusPaidOnline: 'Оплачено онлайн',
    statusPendingPayment: 'Ожидает оплаты',
    methodStripe: 'Stripe',
    methodBalance: 'Баланс аккаунта Rednest',
    methodCards: 'Visa / Mastercard',
    methodGPay: 'Google Pay',
    methodCashierCard: 'Оплата на кассе (Карта / NFC)',
    methodCashierCash: 'Оплата на кассе',
    stripeModalTitle: 'Оплата картой онлайн',
    stripeAmountToPay: 'Сумма к оплате:',
    loadingOptions: 'Загрузка вариантов оплаты...',
    selectSavedCard: 'Выберите сохраненную карту',
    useNewCard: 'Новая карта',
    chooseFromSaved: 'Выбрать из сохраненных карт',
    defaultBadge: 'ОСНОВНАЯ',
    payAmount: 'Оплатить {amount} ₼',
    processing: 'Обработка...',
    cardNumberLabel: 'Номер карты',
    expiryDateLabel: 'Срок действия',
    cvcLabel: 'CVC / CVV',
    cardholderLabel: 'Имя на карте (необязательно)',
    cardLabelLabel: 'Название карты (необязательно)',
    cardholderPlaceholder: 'напр. ELCHIN',
    cardLabelPlaceholder: 'напр. Зарплатная',
    saveCardCheckbox: 'Сохранить карту для будущих платежей',
    agreeToRules: 'Согласен с ',
    paymentRulesLink: 'Правилами оплаты',
    paymentErrorTitle: 'Ошибка оплаты',
    errCardNumberRequired: 'Введите номер карты.',
    errCardNumberDigits: 'Номер карты должен состоять из 16 цифр.',
    errCardNumberInvalid: 'Неверный номер карты.',
    errCardBrandUnsupported: 'Принимаются только Visa и Mastercard.',
    errExpiryRequired: 'Укажите срок действия карты.',
    errExpiryFormat: 'Формат должен быть ММ/ГГ.',
    errExpiryMonth: 'Неверный месяц.',
    errCardExpired: 'Срок действия карты истек.',
    errCvcRequired: 'Введите CVC/CVV код.',
    errCvcDigits: 'Должно быть 3 цифры.',
    errCardholderInvalid: 'Введите корректное имя владельца карты.',
    errAgreedRequired: 'Необходимо согласиться с правилами оплаты.',
    errMaxCardsReached: 'Можно сохранить не более 3 карт. Снимите галочку «Сохранить карту» или удалите одну из существующих.',
    errPaymentFailed: 'Не удалось провести оплату. Попробуйте снова.',
    errPaymentCheckInfo: 'Оплата не прошла. Пожалуйста, проверьте данные карты.',
    errProcessingGeneral: 'Произошла ошибка при обработке платежа.',
  },
  en: {
    stepBadge: 'Checkout & Payment',
    heroTitle: 'Choose Payment Method',
    heroDesc: 'Select how you would like to pay for your order.',
    emptyBasket: 'Your basket is empty. Add items from the menu to place an order.',
    browseMenu: 'Browse Menu',
    inStoreBadge: 'In-Store Pickup',
    payAtCashier: 'Pay at Cashier',
    payAtCashierCounter: 'Pay at Cashier Counter',
    cashierDesc: 'Pay with cash or bank card in person when you pick up your fresh order at the barista counter.',
    cashPayment: 'Cash Payment',
    cardNfc: 'Card & NFC',
    usePromoCodes: 'Use Promo Codes',
    selectedBadge: '✓ Selected',
    chooseCashier: 'Choose Cashier',
    instantBadge: 'Instant & Contactless',
    payOnline: 'Pay Online',
    payOnlineInstantly: 'Pay Online Instantly',
    onlineDesc: 'Pay securely online with your credit/debit card or Rednest balance for immediate preparation.',
    visaMastercard: 'Visa or Mastercard',
    payViaBalance: 'Pay via Balance',
    payViaStripe: 'Pay via Stripe',
    googlePay: 'Google Pay',
    earnCashback: 'Earn Cashback',
    chooseOnline: 'Choose Online',
    selectedPayment: 'Selected Payment:',
    cashierStepDesc: 'Your order will be sent to the baristas and marked for in-store payment upon pickup.',
    onlineStepDesc: 'Proceeding with secure online payment for immediate order confirmation.',
    changeMethod: 'Change Method',
    selectPromo: 'Select Promo Code to Apply:',
    promosAvailable: '{count} available',
    dontUsePromo: "Don't use any promo code",
    itemsCount: 'Items:',
    itemsSuffix: 'items',
    discountLabel: 'Discount:',
    totalToPay: 'Total to Pay:',
    confirmOrder: 'Confirm & Place Order',
    continueOnline: 'Continue to Online Payment',
    placingOrder: 'Placing Order...',
    backToBasket: 'Back to Basket',
    orderFailed: 'Failed to place order. Please try again.',
    orderNetworkError: 'An error occurred while placing your order. Please check your connection.',
    onlineModalTitle: 'Online Payment Service',
    onlineModalDesc: 'Select a payment method',
    cancel: 'Cancel',
    payWithBalance: 'Pay with Balance',
    continueToPayment: 'Continue to Payment',
    popularBadge: 'Popular',
    instantSpeedBadge: 'Instant',
    cardsBadge: 'Cards',
    oneTapBadge: '1-Tap',
    balancePrefix: 'Balance:',
    serviceStripeTitle: 'Pay with Stripe',
    serviceStripeDesc: 'Fast and secure international payment',
    serviceBalanceTitle: 'Rednest Balance',
    serviceBalanceDesc: 'Instant payment from your account balance',
    serviceCardsTitle: 'Visa or Mastercard',
    serviceCardsDesc: 'Debit or credit card payment',
    serviceGPayTitle: 'Google Pay',
    serviceGPayDesc: 'One-tap checkout with Google Pay',
    orderSuccessTitle: 'Order Placed Successfully!',
    orderSuccessDesc: 'Order sent to barista. Show your order number at the counter.',
    orderNumberLabel: 'Order Number',
    mentionAtCounter: 'Mention this at counter',
    promoDiscount: 'Promo Discount',
    cashbackAdded: 'Cashback Added',
    paymentMethodLabel: 'Payment Method',
    backToMenu: 'Back to Menu',
    viewOrders: 'View Orders',
    statusPaidOnline: 'Paid Online',
    statusPendingPayment: 'Pending Payment',
    methodStripe: 'Stripe',
    methodBalance: 'Rednest Account Balance',
    methodCards: 'Visa / Mastercard',
    methodGPay: 'Google Pay',
    methodCashierCard: 'Pay at Cashier (Card / NFC)',
    methodCashierCash: 'Pay at Cashier',
    stripeModalTitle: 'Card & Online Payment',
    stripeAmountToPay: 'Amount to pay:',
    loadingOptions: 'Loading payment options...',
    selectSavedCard: 'Select Saved Card',
    useNewCard: 'Use New Card',
    chooseFromSaved: 'Choose from saved cards',
    defaultBadge: 'DEFAULT',
    payAmount: 'Pay {amount} ₼',
    processing: 'Processing...',
    cardNumberLabel: 'Card Number',
    expiryDateLabel: 'Expiry Date',
    cvcLabel: 'CVC / CVV',
    cardholderLabel: 'Cardholder (Optional)',
    cardLabelLabel: 'Card Label (Optional)',
    cardholderPlaceholder: 'e.g. ELCHIN',
    cardLabelPlaceholder: 'e.g. Salary Card',
    saveCardCheckbox: 'Save card for future payments',
    agreeToRules: 'Agree to ',
    paymentRulesLink: 'Payment Rules',
    paymentErrorTitle: 'Payment Error',
    errCardNumberRequired: 'Card number is required.',
    errCardNumberDigits: 'Card number must be 16 digits.',
    errCardNumberInvalid: 'Invalid card number.',
    errCardBrandUnsupported: 'Only Visa and Mastercard are accepted.',
    errExpiryRequired: 'Expiry date is required.',
    errExpiryFormat: 'Format must be MM/YY.',
    errExpiryMonth: 'Invalid month.',
    errCardExpired: 'Card has expired.',
    errCvcRequired: 'CVC is required.',
    errCvcDigits: 'Must be 3 digits.',
    errCardholderInvalid: 'Please enter a valid cardholder name.',
    errAgreedRequired: 'You must agree to the payment rules.',
    errMaxCardsReached: 'You can only save up to 3 payment cards. Please uncheck "Save card" or delete an existing card.',
    errPaymentFailed: 'Payment failed. Please try again.',
    errPaymentCheckInfo: 'Payment failed. Please check your card information.',
    errProcessingGeneral: 'An error occurred during payment processing.',
  },
};

export const getOrderTranslation = (lang, id) => {
  return translations[lang]?.[id] || translations.az?.[id] || translations.en?.[id] || id;
};
