export const translations = {
  ru: {
    "addr_hero_title": "Адреса доставки",
    "addr_hero_desc": "Управление адресами доставки, выбор основного адреса и инструкции для курьера",
    "addr_btn_add": "Добавить новый адрес",
    "addr_limit_reached": "Вы можете сохранить максимум 3 адреса доставки. Пожалуйста, удалите существующий адрес, чтобы добавить новый.",
    "addr_limit_title": "Лимит адресов",
    "addr_loading": "Загрузка сохраненных адресов...",
    "addr_error_load": "Не удалось загрузить сохраненные адреса доставки.",
    "addr_try_again": "Попробовать снова",
    "addr_added_on": "Добавлен",
    "addr_fallback_title": "Адрес доставки",
    "addr_badge_default": "По умолчанию",
    "addr_city": "Город",
    "addr_apt": "Кв. / Этаж",
    "addr_phone": "Телефон",
    "addr_set_default": "Сделать основным",
    "addr_setting_default": "Сохранение...",
    "addr_edit": "Редактировать",
    "addr_delete": "Удалить",
    "addr_toast_updated": "Адрес успешно обновлен!",
    "addr_toast_added": "Новый адрес доставки добавлен!",
    "addr_toast_default": "установлен как основной адрес!",
    "addr_toast_deleted": "Адрес успешно удален.",
    "addr_this_address": "этот адрес",

    "modal_title_edit": "Редактировать адрес",
    "modal_title_add": "Добавить адрес доставки",
    "modal_desc_edit": "Обновите данные доставки и комментарий для курьера",
    "modal_desc_add": "Сохраните новый адрес для быстрого оформления заказа",
    "modal_label_title": "Название",
    "modal_ph_title": "например: Дом, Работа, Студия...",
    "modal_label_city": "Город",
    "modal_ph_city": "например: Баку",
    "modal_label_street": "Улица и номер дома",
    "modal_ph_street": "например: ул. Низами 48, дом 2",
    "modal_label_apt": "Квартира / Этаж / Подъезд",
    "modal_ph_apt": "например: кв. 14, этаж 3, под. 1",
    "modal_label_phone": "Контактный телефон",
    "modal_ph_phone": "например: +994 50 123 45 67",
    "modal_label_notes": "Инструкции для курьера / Код домофона",
    "modal_ph_notes": "например: Код домофона #1234. Оставьте у двери.",
    "modal_toggle_default": "Сделать основным",
    "modal_btn_cancel": "Отмена",
    "modal_btn_save": "Сохранить изменения",
    "modal_btn_add": "Добавить адрес",
    "modal_btn_saving": "Сохранение...",
    "modal_btn_adding": "Добавление...",
    "modal_err_street": "Пожалуйста, укажите улицу и номер дома.",
    "modal_err_city": "Пожалуйста, укажите город.",
    "modal_err_phone": "Пожалуйста, укажите контактный телефон."
  },
  en: {
    "addr_hero_title": "Delivery Addresses",
    "addr_hero_desc": "Manage your delivery locations, set default shipping destination, and configure courier instructions",
    "addr_btn_add": "Add New Address",
    "addr_limit_reached": "You can only save up to 3 delivery addresses. Please delete an existing address to add a new one.",
    "addr_limit_title": "Address Limit",
    "addr_loading": "Loading your saved addresses...",
    "addr_error_load": "Failed to load saved delivery addresses.",
    "addr_try_again": "Try Again",
    "addr_added_on": "Added",
    "addr_fallback_title": "Delivery Address",
    "addr_badge_default": "Default",
    "addr_city": "City",
    "addr_apt": "Apt / Floor",
    "addr_phone": "Phone",
    "addr_set_default": "Set Default",
    "addr_setting_default": "Setting...",
    "addr_edit": "Edit",
    "addr_delete": "Delete",
    "addr_toast_updated": "Address updated successfully!",
    "addr_toast_added": "New delivery address added!",
    "addr_toast_default": "set as default address!",
    "addr_toast_deleted": "Address removed successfully.",
    "addr_this_address": "this address",

    "modal_title_edit": "Edit Delivery Address",
    "modal_title_add": "Add Delivery Address",
    "modal_desc_edit": "Update your delivery details and instructions",
    "modal_desc_add": "Save a new delivery address for faster checkout",
    "modal_label_title": "Title",
    "modal_ph_title": "e.g. Home, Office, Gym...",
    "modal_label_city": "City",
    "modal_ph_city": "e.g. Baku",
    "modal_label_street": "Street Address",
    "modal_ph_street": "e.g. Nizami Street 48, Building 2",
    "modal_label_apt": "Apt / Floor / Entrance",
    "modal_ph_apt": "e.g. Apt 14, Floor 3, Ent. 1",
    "modal_label_phone": "Contact Phone",
    "modal_ph_phone": "e.g. +994 50 123 45 67",
    "modal_label_notes": "Courier Instructions / Intercom Code",
    "modal_ph_notes": "e.g. Intercom code #1234. Please leave at door.",
    "modal_toggle_default": "Set as default",
    "modal_btn_cancel": "Cancel",
    "modal_btn_save": "Save Changes",
    "modal_btn_add": "Add Address",
    "modal_btn_saving": "Saving...",
    "modal_btn_adding": "Adding...",
    "modal_err_street": "Please enter your street address.",
    "modal_err_city": "Please enter your city.",
    "modal_err_phone": "Please enter your contact phone number."
  },
  az: {
    "addr_hero_title": "Çatdırılma ünvanları",
    "addr_hero_desc": "Çatdırılma məkanlarınızı idarə edin, əsas ünvanı seçin və kuryer üçün təlimatlar qeyd edin",
    "addr_btn_add": "Yeni ünvan əlavə et",
    "addr_limit_reached": "Maksimum 3 çatdırılma ünvanı saxlaya bilərsiniz. Yenisini əlavə etmək üçün mövcud ünvanı silin.",
    "addr_limit_title": "Ünvan limiti",
    "addr_loading": "Yadda saxlanılmış ünvanlar yüklənir...",
    "addr_error_load": "Yadda saxlanılmış çatdırılma ünvanlarını yükləmək mümkün olmadı.",
    "addr_try_again": "Yenidən cəhd edin",
    "addr_added_on": "Əlavə edilib",
    "addr_fallback_title": "Çatdırılma ünvanı",
    "addr_badge_default": "Əsas",
    "addr_city": "Şəhər",
    "addr_apt": "Mənzil / Mərtəbə",
    "addr_phone": "Telefon",
    "addr_set_default": "Əsas et",
    "addr_setting_default": "Dəyişdirilir...",
    "addr_edit": "Düzəliş et",
    "addr_delete": "Sil",
    "addr_toast_updated": "Ünvan uğurla yeniləndi!",
    "addr_toast_added": "Yeni çatdırılma ünvanı əlavə edildi!",
    "addr_toast_default": "əsas ünvan olaraq təyin edildi!",
    "addr_toast_deleted": "Ünvan uğurla silindi.",
    "addr_this_address": "bu ünvan",

    "modal_title_edit": "Ünvanı redaktə et",
    "modal_title_add": "Çatdırılma ünvanı əlavə et",
    "modal_desc_edit": "Çatdırılma detallarını və kuryer təlimatlarını yeniləyin",
    "modal_desc_add": "Sürətli sifariş üçün yeni çatdırılma ünvanı yadda saxlayın",
    "modal_label_title": "Başlıq",
    "modal_ph_title": "məs: Ev, İş, Zal...",
    "modal_label_city": "Şəhər",
    "modal_ph_city": "məs: Bakı",
    "modal_label_street": "Küçə və ev nömrəsi",
    "modal_ph_street": "məs: Nizami küç. 48, bina 2",
    "modal_label_apt": "Mənzil / Mərtəbə / Blok",
    "modal_ph_apt": "məs: mənz. 14, mərt. 3, blok 1",
    "modal_label_phone": "Əlaqə nömrəsi",
    "modal_ph_phone": "məs: +994 50 123 45 67",
    "modal_label_notes": "Kuryer üçün qeydlər / Damafon kodu",
    "modal_ph_notes": "məs: Damafon kodu #1234. Qapıda qoyun.",
    "modal_toggle_default": "Əsas ünvan et",
    "modal_btn_cancel": "Ləğv et",
    "modal_btn_save": "Yadda saxla",
    "modal_btn_add": "Ünvanı əlavə et",
    "modal_btn_saving": "Saxlanılır...",
    "modal_btn_adding": "Əlavə edilir...",
    "modal_err_street": "Zəhmət olmasa küçə ünvanınızı qeyd edin.",
    "modal_err_city": "Zəhmət olmasa şəhəri qeyd edin.",
    "modal_err_phone": "Zəhmət olmasa əlaqə nömrəsini qeyd edin."
  }
};

export const getAddressesTranslation = (lang, dataId) => {
  const dict = translations[lang] || translations.az || translations.ru;
  return dict[dataId] || (translations.en && translations.en[dataId]) || dataId;
};
