// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rednest.Core.Entities;
using Rednest.Infrastructure.Data;

#nullable disable

namespace Rednest.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816134128_AddProducts")]
    partial class AddProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rednest.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            Category = "Main Drinks",
                            Description = "Quenches thirst, invigorates, and is an ideal choice for relaxation.",
                            ImageUrl = "https://tlcehlxztgewbidcvwye.supabase.co/storage/v1/object/public/admin-files/database/tea_7654329000.webp",
                            Name = "Tea",
                            Price = 1.49m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            Category = "Main Drinks",
                            Description = "A perfect choice to start the day energetically with its thick and strong taste. A favorite of true coffee lovers.",
                            ImageUrl = "https://tlcehlxztgewbidcvwye.supabase.co/storage/v1/object/public/admin-files/database/espresso_6854930222.webp",
                            Name = "Espresso",
                            Price = 2.89m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            Category = "Main Drinks",
                            Description = "A light and delicate flavor. Prepared by adding water to espresso, its taste is simple yet classic.",
                            ImageUrl = "https://tlcehlxztgewbidcvwye.supabase.co/storage/v1/object/public/admin-files/database/americano_1786885347.webp",
                            Name = "Americano",
                            Price = 2.89m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000004"),
                            Category = "Main Drinks",
                            Description = "Soft espresso mixed with fine milk foam. For those who love a warm and delicate taste.",
                            ImageUrl = "https://tlcehlxztgewbidcvwye.supabase.co/storage/v1/object/public/admin-files/database/latte_6543223589.webp",
                            Name = "Latte",
                            Price = 3.49m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0001-0001-000000000005"),
                            Category = "Main Drinks",
                            Description = "The perfect balance of coffee and milk foam. The soft foam on top brings happiness with every sip.",
                            ImageUrl = "https://tlcehlxztgewbidcvwye.supabase.co/storage/v1/object/public/admin-files/database/cappuccino_8765432354.webp",
                            Name = "Cappuccino",
                            Price = 3.49m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0002-0002-000000000001"),
                            Category = "Specialty Drinks",
                            Description = "Special Rednest recipe: The harmony of latte and strawberry syrup. A sweet and romantic taste.",
                            ImageUrl = "https://tlcehlxztgewbidcvwye.supabase.co/storage/v1/object/public/admin-files/database/red_latte_9876543221.webp",
                            Name = "Red Latte",
                            Price = 3.75m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0002-0002-000000000002"),
                            Category = "Specialty Drinks",
                            Description = "Cappuccino enriched with the sweetness of caramel and the aroma of hazelnut. Like a warm hug.",
                            ImageUrl = "https://tlcehlxztgewbidcvwye.supabase.co/storage/v1/object/public/admin-files/database/nest_cappuccino_9876543290.webp",
                            Name = "Nest Cappuccino",
                            Price = 4.25m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0002-0002-0002-000000000003"),
                            Category = "Specialty Drinks",
                            Description = "A drink that warms your soul with the aroma and softness of thick chocolate. A taste that brings back childhood memories.",
                            ImageUrl = "https://tlcehlxztgewbidcvwye.supabase.co/storage/v1/object/public/admin-files/database/hot_chocolate_7690568000.webp",
                            Name = "Hot Chocolate",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-0003-0003-000000000001"),
                            Category = "Desserts",
                            Description = "A delicate pastry dessert filled with fragrant cream and covered with a fine layer. Every bite brings a light sweetness and pleasant taste.",
                            ImageUrl = "https://tlcehlxztgewbidcvwye.supabase.co/storage/v1/object/public/admin-files/database/eclair_8439200222.webp",
                            Name = "Eclair",
                            Price = 2.25m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-0003-0003-000000000002"),
                            Category = "Desserts",
                            Description = "An unforgettable French classic with butter and taste in a light, flaky pastry.",
                            ImageUrl = "https://tlcehlxztgewbidcvwye.supabase.co/storage/v1/object/public/admin-files/database/croissant_7654320922.webp",
                            Name = "Croissant",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0003-0003-0003-000000000003"),
                            Category = "Desserts",
                            Description = "Soft, sweet, and satisfying. The best companion to every cup of coffee.",
                            ImageUrl = "https://tlcehlxztgewbidcvwye.supabase.co/storage/v1/object/public/admin-files/database/muffin_7965430339.webp",
                            Name = "Muffin",
                            Price = 1.59m
                        });
                });

            modelBuilder.Entity("Rednest.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Rednest.Core.Entities.UserPromo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<PromoCodes>("Codes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<PromoDates>("Dates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<PrizeInfo>("PrizeInfo")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPromos");
                });

            modelBuilder.Entity("Rednest.Core.Entities.UserSession", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RegistrationIp")
                        .HasColumnType("text");

                    b.Property<List<SessionEntry>>("Sessions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("UserId");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Rednest.Core.Entities.UserPromo", b =>
                {
                    b.HasOne("Rednest.Core.Entities.User", "User")
                        .WithMany("Promos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rednest.Core.Entities.UserSession", b =>
                {
                    b.HasOne("Rednest.Core.Entities.User", "User")
                        .WithOne("Session")
                        .HasForeignKey("Rednest.Core.Entities.UserSession", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rednest.Core.Entities.User", b =>
                {
                    b.Navigation("Promos");

                    b.Navigation("Session");
                });
#pragma warning restore 612, 618
        }
    }
}
