export const translations = {
  az: {
    searchPlaceholder: 'Məhsul adı və ya kateqoriyaya görə axtarın...',
    clearSearch: 'Axtarışı təmizlə',
    cashier: 'Kassir:',
    unknownUser: 'Naməlum istifadəçi',

    categories: {
      'All': 'Hamısı',
      'Main Drinks': 'Əsas içkilər',
      'Specialty Drinks': 'Xüsusi içkilər',
      'Desserts': 'Desertlər',
      'Coffee': 'Qəhvə',
      'Tea': 'Çay',
      'Drinks': 'İçkilər',
      'Bakery': 'Şirniyyat',
      'Food': 'Qida',
      'Sandwiches': 'Sendviçlər',
      'General': 'Ümumi',
    },

    promoCodes: 'Promo',
    promoActive: 'Promokod aktivdir',
    promoActiveCount: (count = 1) => `Promo (${count})`,

    loadingCatalog: 'Kataloq yüklənir...',
    noProductsFound: 'Məhsul tapılmadı',
    noProductsDesc: 'Axtarış sorğusunu dəyişin və ya başqa kateqoriya seçin',
    resetFilters: 'Filtrləri sıfırla',
    productDefault: 'Məhsul',

    electronicReceipt: 'Elektron qəbz',
    clearReceipt: 'Təmizlə',
    clearReceiptTitle: 'Qəbzi təmizlə',
    receiptEmpty: 'Qəbz boşdur',
    receiptEmptyDesc: 'Kataloqdan içki və ya desertləri seçin',
    decreaseQty: 'Sayı azalt',
    increaseQty: 'Sayı artır',
    removeItem: 'Məhsulu sil',
    removePromo: 'Promokodu sil',
    usePromoCode: 'Promokod tətbiq et',
    subtotal: 'Məbləğ:',
    promoDiscount: 'Promokod endirimi',
    promoDiscountLabel: (code) => code ? `Promokod endirimi (${code}):` : 'Promokod endirimi:',
    total: 'Yekun:',
    itemsSuffix: 'məhsul',

    confirm: 'Təsdiqlə',
    cash: 'Nağd',
    card: 'Qeyri-nağd',
    cashDesc: 'Nağd pulla ödəniş',
    cardDesc: 'Bank kartı və ya POS terminal ilə',
    cancel: 'Ləğv et',
    cancelSplit: 'Bölünməni ləğv et',
    selectPayMethod: 'Ödəniş üsulu',
    totalToPay: 'Ödəniləcək yekun:',
    currentOrder: 'Cari sifariş',
    closeReceipt: 'Qəbzi bağla',
    closeModal: 'Bağla',

    promoModalTitle: 'Promokod axtarışı',
    promoModalSubtitle: 'Barkod və ya promokod nömrəsi ilə axtarış',
    promoInputPlaceholder: 'Barkod və ya promokod...',
    search: 'Axtar',
    searching: 'Axtarılır...',
    searchingDb: 'Bazada promokodlar axtarılır...',
    scanOrEnter: 'Barkodu skan edin və ya promokodu daxil edin',
    scanOrEnterDesc: 'Etibarlılığı, endirim məbləğini və hesab sahibini yoxlamaq üçün müştərinin promokodunu və ya barkodunu daxil edin.',
    noActivePromo: 'Aktiv promokod tapılmadı',
    noActivePromoDesc: (query) => `"${query}" sorğusuna uyğun aktiv promokod tapılmadı.`,
    active: 'Aktiv',
    expired: 'Vaxtı bitib',
    inactive: 'Qeyri-aktiv',
    accountOwner: 'Hesab sahibi',
    unclaimedPublic: 'Ümumi promokod',
    anonymousCustomer: 'Anonim müştəri',
    promoCodeLabel: 'Promokod',
    barcodeLabel: 'Barkod nömrəsi',
    discountLabel: 'Endirim',
    cashbackLabel: 'Keşbek',
    appliedToReceipt: 'Qəbzə tətbiq edildi',
    removeFromReceipt: 'Qəbzdən çıxar',
    remove: 'Sil',
    applyToOrder: 'Sifarişə tətbiq et',
    activated: 'Aktivləşdirilib:',
    expires: 'Bitmə tarixi:',
    promoSearchError: 'Promokodları axtarmaq mümkün olmadı.',
    promoNetworkError: 'Promokod axtarışı zamanı şəbəkə xətası baş verdi.',

    freeDrink: 'Pulsuz içki',
    freeDessert: 'Pulsuz desert',
    superPrize: 'Super hədiyyə',
    discount25: '25% endirim',
    discount50: '50% endirim',

    receiptEmptyToast: 'Qəbz boşdur! Zəhmət olmasa məhsul əlavə edin.',
    promoAppliedToast: (code) => `${code} promokodu tətbiq edildi!`,
    promoRemovedToast: 'Promokod qəbzdən silindi.',
    orderFailedToast: 'Sifarişi rəsmiləşdirmək mümkün olmadı.',
    orderNetworkErrorToast: 'Sifariş zamanı şəbəkə xətası baş verdi.',
    orderConfirmedCash: (amt, promo) =>
      promo ? `Sifariş təsdiqləndi (Nağd): ${amt} ₼ (${promo})` : `Sifariş təsdiqləndi (Nağd): ${amt} ₼`,
    orderConfirmedCard: (amt, promo) =>
      promo ? `Sifariş təsdiqləndi (Qeyri-nağd): ${amt} ₼ (${promo})` : `Sifariş təsdiqləndi (Qeyri-nağd): ${amt} ₼`,

    received: 'Qəbul edildi:',
    change: 'Qalıq:',
    payByCard: 'Kartla ödə',
    cashPayment: 'Nağd ödəniş',
    backspace: 'Sil',

    history: {
      title: 'Kassa Tarixçəsi',
      subtitle: 'Bütün kassa əməliyyatlarının və çeklərin reyestri',
      backToCashbox: 'Kassaya qayıt',
      totalOrders: 'Cəmi sifariş',
      totalRevenue: 'Ümumi gəlir',
      cashTotal: 'Nağd ödənişlər',
      cardTotal: 'Kart ödənişləri',
      allStatuses: 'Bütün statuslar',
      allMethods: 'Bütün üsullar',
      allTime: 'Bütün dövr',
      today: 'Bu gün',
      yesterday: 'Dünən',
      thisWeek: 'Son 7 gün',
      thisMonth: 'Son 30 gün',
      searchPlaceholder: 'Sifariş ID, promokod və ya qeyd...',
      orderId: 'Sifariş №',
      date: 'Tarix',
      cashier: 'Kassir',
      items: 'Məhsullar',
      payment: 'Ödəniş',
      status: 'Status',
      total: 'Məbləğ',
      actions: 'Əməliyyatlar',
      viewDetails: 'Ətraflı',
      orderDetails: 'Sifarişin təfərrüatları',
      note: 'Qeyd',
      addNote: 'Qeyd əlavə et',
      saveChanges: 'Yadda saxla',
      changeStatus: 'Statusu dəyiş',
      deleteOrder: 'Sifarişi sil',
      confirmDelete: 'Sifarişi silmək istədiyinizdən əminsiniz?',
      deleteWarning: 'Bu əməliyyat geri qaytarıla bilməz.',
      noOrdersFound: 'Sifariş tapılmadı',
      noOrdersDesc: 'Axtarış parametrlərini dəyişərək yenidən yoxlayın.',
      loadingHistory: 'Tarixçə yüklənir...',
      loadError: 'Tarixçəni yükləmək mümkün olmadı',
      statusUpdated: 'Status uğurla yeniləndi',
      orderDeleted: 'Sifariş uğurla silindi',
      refresh: 'Yenilə',
      itemCount: (c) => `${c} məhsul`,
      subtotal: 'Məhsul məbləği:',
      discount: 'Endirim:',
      initial: 'İlkin məbləğ:',
      editedBy: 'Düzəliş edən:',
      cash: 'Nağd',
      card: 'Kart',
      statusSuccess: 'Uğurlu',
      statusCancelled: 'Ləğv edildi',
      statusRefunded: 'Qaytarıldı',
      statusPending: 'Gözləmədə',
      statusProcessing: 'İcrada',
      historyButton: 'Tarixçə',
      pageOf: (p, total) => `Səhifə ${p} / ${total}`
    }
  },

  ru: {
    searchPlaceholder: 'Поиск товаров по названию или категории...',
    clearSearch: 'Очистить поиск',
    cashier: 'Кассир:',
    unknownUser: 'Неизвестный пользователь',

    categories: {
      'All': 'Все',
      'Main Drinks': 'Основные напитки',
      'Specialty Drinks': 'Особые напитки',
      'Desserts': 'Десерты',
      'Coffee': 'Кофе',
      'Tea': 'Чай',
      'Drinks': 'Напитки',
      'Bakery': 'Выпечка',
      'Food': 'Еда',
      'Sandwiches': 'Сэндвичи',
      'General': 'Общее',
    },

    promoCodes: 'Promo',
    promoActive: 'Промокод активен',
    promoActiveCount: (count = 1) => `Promo (${count})`,

    loadingCatalog: 'Загрузка каталога...',
    noProductsFound: 'Товары не найдены',
    noProductsDesc: 'Попробуйте изменить поисковый запрос или выберите другую категорию',
    resetFilters: 'Сбросить фильтры',
    productDefault: 'Товар',

    electronicReceipt: 'Электронный чек',
    clearReceipt: 'Очистить',
    clearReceiptTitle: 'Очистить чек',
    receiptEmpty: 'Чек пуст',
    receiptEmptyDesc: 'Выберите напитки или десерты из каталога',
    decreaseQty: 'Уменьшить количество',
    increaseQty: 'Увеличить количество',
    removeItem: 'Удалить позицию',
    removePromo: 'Удалить промокод',
    usePromoCode: 'Применить промокод',
    subtotal: 'Подытог:',
    promoDiscount: 'Скидка по промокоду',
    promoDiscountLabel: (code) => code ? `Скидка по промокоду (${code}):` : 'Скидка по промокоду:',
    total: 'Итого:',
    itemsSuffix: 'товаров',

    confirm: 'Подтвердить',
    cash: 'Наличными',
    card: 'Безналичными',
    cashDesc: 'Оплата наличными средствами',
    cardDesc: 'Банковской картой или POS-терминалом',
    cancel: 'Отмена',
    cancelSplit: 'Отменить выбор',
    selectPayMethod: 'Способ оплаты',
    totalToPay: 'Сумма к оплате:',
    currentOrder: 'Текущий заказ',
    closeReceipt: 'Закрыть чек',
    closeModal: 'Закрыть',

    promoModalTitle: 'Поиск промокода',
    promoModalSubtitle: 'Поиск по штрихкоду или номеру промокода',
    promoInputPlaceholder: 'Штрихкод или промокод...',
    search: 'Поиск',
    searching: 'Поиск...',
    searchingDb: 'Поиск промокодов в базе данных...',
    scanOrEnter: 'Сканируйте или введите штрихкод / код',
    scanOrEnterDesc: 'Введите промокод или штрихкод клиента для проверки срока действия, размера скидки и владельца.',
    noActivePromo: 'Активный промокод не найден',
    noActivePromoDesc: (query) => `По запросу «${query}» активных промокодов не найдено.`,
    active: 'Активен',
    expired: 'Истек',
    inactive: 'Неактивен',
    accountOwner: 'Владелец аккаунта',
    unclaimedPublic: 'Общий промокод',
    anonymousCustomer: 'Анонимный клиент',
    promoCodeLabel: 'Промокод',
    barcodeLabel: 'Штрихкод',
    discountLabel: 'Скидка',
    cashbackLabel: 'Кэшбэк',
    appliedToReceipt: 'Применен к чеку',
    removeFromReceipt: 'Удалить из чека',
    remove: 'Удалить',
    applyToOrder: 'Применить к заказу',
    activated: 'Активирован:',
    expires: 'Истекает:',
    promoSearchError: 'Не удалось выполнить поиск промокодов.',
    promoNetworkError: 'Ошибка сети при поиске промокодов.',

    freeDrink: 'Бесплатный напиток',
    freeDessert: 'Бесплатный десерт',
    superPrize: 'Суперприз',
    discount25: 'Скидка 25%',
    discount50: 'Скидка 50%',

    receiptEmptyToast: 'Чек пуст! Пожалуйста, добавьте товары.',
    promoAppliedToast: (code) => `Промокод ${code} применен!`,
    promoRemovedToast: 'Промокод удален из чека.',
    orderFailedToast: 'Не удалось оформить заказ.',
    orderNetworkErrorToast: 'Ошибка сети при оформлении заказа.',
    orderConfirmedCash: (amt, promo) =>
      promo ? `Заказ оформлен (Наличные): ${amt} ₼ (Промокод ${promo})` : `Заказ оформлен (Наличные): ${amt} ₼`,
    orderConfirmedCard: (amt, promo) =>
      promo ? `Заказ оформлен (Безналичные): ${amt} ₼ (Промокод ${promo})` : `Заказ оформлен (Безналичные): ${amt} ₼`,

    received: 'Получено:',
    change: 'Сдача:',
    payByCard: 'Оплата картой',
    cashPayment: 'Оплата наличными',
    backspace: 'Стереть',

    history: {
      title: 'История кассы',
      subtitle: 'Реестр всех кассовых операций и чеков',
      backToCashbox: 'Вернуться в кассу',
      totalOrders: 'Всего заказов',
      totalRevenue: 'Общая выручка',
      cashTotal: 'Наличными',
      cardTotal: 'Картой',
      allStatuses: 'Все статусы',
      allMethods: 'Все способы',
      allTime: 'За всё время',
      today: 'Сегодня',
      yesterday: 'Вчера',
      thisWeek: 'За 7 дней',
      thisMonth: 'За 30 дней',
      searchPlaceholder: 'ID заказа, промокод или примечание...',
      orderId: 'Заказ №',
      date: 'Дата',
      cashier: 'Кассир',
      items: 'Товары',
      payment: 'Оплата',
      status: 'Статус',
      total: 'Сумма',
      actions: 'Действия',
      viewDetails: 'Подробнее',
      orderDetails: 'Детали заказа',
      note: 'Примечание',
      addNote: 'Добавить примечание',
      saveChanges: 'Сохранить',
      changeStatus: 'Сменить статус',
      deleteOrder: 'Удалить заказ',
      confirmDelete: 'Вы уверены, что хотите удалить заказ?',
      deleteWarning: 'Это действие нельзя отменить.',
      noOrdersFound: 'Заказы не найдены',
      noOrdersDesc: 'Попробуйте изменить параметры фильтрации или поисковый запрос.',
      loadingHistory: 'Загрузка истории...',
      loadError: 'Не удалось загрузить историю',
      statusUpdated: 'Статус успешно обновлен',
      orderDeleted: 'Заказ успешно удален',
      refresh: 'Обновить',
      itemCount: (c) => `${c} шт.`,
      subtotal: 'Подытог:',
      discount: 'Скидка:',
      initial: 'Исходная сумма:',
      editedBy: 'Изменил:',
      cash: 'Наличные',
      card: 'Карта',
      statusSuccess: 'Успешно',
      statusCancelled: 'Отменен',
      statusRefunded: 'Возврат',
      statusPending: 'В ожидании',
      statusProcessing: 'В обработке',
      historyButton: 'История',
      pageOf: (p, total) => `Страница ${p} из ${total}`
    }
  },

  en: {
    searchPlaceholder: 'Search products by name or category...',
    clearSearch: 'Clear search',
    cashier: 'Cashier:',
    unknownUser: 'Unknown User',

    categories: {
      'All': 'All',
      'Main Drinks': 'Main Drinks',
      'Specialty Drinks': 'Specialty Drinks',
      'Desserts': 'Desserts',
      'Coffee': 'Coffee',
      'Tea': 'Tea',
      'Drinks': 'Drinks',
      'Bakery': 'Bakery',
      'Food': 'Food',
      'Sandwiches': 'Sandwiches',
      'General': 'General',
    },

    promoCodes: 'Promo',
    promoActive: 'Promo code active',
    promoActiveCount: (count = 1) => `Promo (${count})`,

    loadingCatalog: 'Loading catalog...',
    noProductsFound: 'No Products Found',
    noProductsDesc: 'Try adjusting your search query or select a different category',
    resetFilters: 'Reset Filters',
    productDefault: 'Product',

    electronicReceipt: 'Electronic Receipt',
    clearReceipt: 'Clear',
    clearReceiptTitle: 'Clear receipt',
    receiptEmpty: 'Receipt is empty',
    receiptEmptyDesc: 'Select beverages or desserts from the catalog',
    decreaseQty: 'Decrease quantity',
    increaseQty: 'Increase quantity',
    removeItem: 'Remove item',
    removePromo: 'Remove promo code',
    usePromoCode: 'Use Promo Code',
    subtotal: 'Subtotal:',
    promoDiscount: 'Promo Discount',
    promoDiscountLabel: (code) => code ? `Promo Discount (${code}):` : 'Promo Discount:',
    total: 'Total:',
    itemsSuffix: 'items',

    confirm: 'Confirm',
    cash: 'Cash',
    card: 'Card',
    cashDesc: 'Cash payment with banknotes or coins',
    cardDesc: 'Debit / Credit card or POS terminal',
    cancel: 'Cancel',
    cancelSplit: 'Cancel split',
    selectPayMethod: 'Payment Method',
    totalToPay: 'Total amount:',
    currentOrder: 'Current Order',
    closeReceipt: 'Close receipt',
    closeModal: 'Close',

    promoModalTitle: 'Promo Code Lookup',
    promoModalSubtitle: 'Search by barcode or promo code number',
    promoInputPlaceholder: 'Barcode or promo code...',
    search: 'Search',
    searching: 'Searching...',
    searchingDb: 'Searching promo codes in database...',
    scanOrEnter: 'Scan or enter barcode / code',
    scanOrEnterDesc: 'Enter customer\'s promo code or barcode to check validity, discount amount, and account owner.',
    noActivePromo: 'No active promo code found',
    noActivePromoDesc: (query) => `No active promo codes match "${query}".`,
    active: 'Active',
    expired: 'Expired',
    inactive: 'Inactive',
    accountOwner: 'Account Owner',
    unclaimedPublic: 'Unclaimed (Public Promo)',
    anonymousCustomer: 'Anonymous Customer',
    promoCodeLabel: 'Promo Code',
    barcodeLabel: 'Barcode Number',
    discountLabel: 'Discount',
    cashbackLabel: 'Cashback',
    appliedToReceipt: 'Applied to Receipt',
    removeFromReceipt: 'Remove from receipt',
    remove: 'Remove',
    applyToOrder: 'Apply to Order',
    activated: 'Activated:',
    expires: 'Expires:',
    promoSearchError: 'Failed to search promo codes.',
    promoNetworkError: 'Network error while searching promo codes.',

    freeDrink: 'Free Drink',
    freeDessert: 'Free Dessert',
    superPrize: 'Super Prize',
    discount25: '25% Off Order',
    discount50: '50% Off Order',

    receiptEmptyToast: 'Receipt is empty! Please add products.',
    promoAppliedToast: (code) => `Promo code ${code} applied!`,
    promoRemovedToast: 'Promo code removed from receipt.',
    orderFailedToast: 'Failed to process order.',
    orderNetworkErrorToast: 'Network error while processing order.',
    orderConfirmedCash: (amt, promo) =>
      promo ? `Order confirmed (Cash): ${amt} ₼ (Promo ${promo} redeemed)` : `Order confirmed (Cash): ${amt} ₼`,
    orderConfirmedCard: (amt, promo) =>
      promo ? `Order confirmed (Card): ${amt} ₼ (Promo ${promo} redeemed)` : `Order confirmed (Card): ${amt} ₼`,

    received: 'Received:',
    change: 'Change:',
    payByCard: 'Pay by Card',
    cashPayment: 'Cash Payment',
    backspace: 'Backspace',

    history: {
      title: 'Cashbox History',
      subtitle: 'Registry of all POS transactions and receipts',
      backToCashbox: 'Back to Cashbox',
      totalOrders: 'Total Orders',
      totalRevenue: 'Total Revenue',
      cashTotal: 'Cash',
      cardTotal: 'Card',
      allStatuses: 'All Statuses',
      allMethods: 'All Methods',
      allTime: 'All Time',
      today: 'Today',
      yesterday: 'Yesterday',
      thisWeek: 'Last 7 Days',
      thisMonth: 'Last 30 Days',
      searchPlaceholder: 'Search Order ID, promo code, note...',
      orderId: 'Order #',
      date: 'Date',
      cashier: 'Cashier',
      items: 'Items',
      payment: 'Payment',
      status: 'Status',
      total: 'Total',
      actions: 'Actions',
      viewDetails: 'Details',
      orderDetails: 'Order Details',
      note: 'Note',
      addNote: 'Add Note',
      saveChanges: 'Save Changes',
      changeStatus: 'Change Status',
      deleteOrder: 'Delete Order',
      confirmDelete: 'Are you sure you want to delete this order?',
      deleteWarning: 'This action cannot be undone.',
      noOrdersFound: 'No Orders Found',
      noOrdersDesc: 'Try adjusting your filters or search query.',
      loadingHistory: 'Loading history...',
      loadError: 'Failed to load history',
      statusUpdated: 'Status successfully updated',
      orderDeleted: 'Order successfully deleted',
      refresh: 'Refresh',
      itemCount: (c) => `${c} items`,
      subtotal: 'Subtotal:',
      discount: 'Discount:',
      initial: 'Initial amount:',
      editedBy: 'Edited by:',
      cash: 'Cash',
      card: 'Card',
      statusSuccess: 'Success',
      statusCancelled: 'Cancelled',
      statusRefunded: 'Refunded',
      statusPending: 'Pending',
      statusProcessing: 'Processing',
      historyButton: 'History',
      pageOf: (p, total) => `Page ${p} of ${total}`
    }
  },
};

export const getCashboxTranslation = (lang) => {
  return translations[lang] || translations.az;
};
