export const translations = {
  ru: {
    "sessions_hero_title": "Активные сессии",
    "sessions_hero_desc": "Управление подключенными устройствами, мониторинг входов в браузер и безопасность аккаунта Rednest",
    "sessions_loading": "Загрузка активных сессий...",
    "sessions_try_again": "Попробовать снова",
    "sessions_empty_title": "Сессии не найдены",
    "sessions_empty_desc": "Для вашего аккаунта пока не зафиксировано активных сессий устройств.",
    "sessions_empty_btn": "Вернуться в профиль",
    "sessions_unknown_device": "Неизвестное устройство",
    "sessions_unknown_os": "Неизвестная ОС",
    "sessions_badge_current": "Это устройство",
    "sessions_badge_active": "Активна",
    "sessions_badge_terminated": "Завершена",
    "sessions_detail_location": "Местоположение",
    "sessions_unknown_location": "Неизвестное местоположение",
    "sessions_detail_ip": "IP-адрес",
    "sessions_detail_created": "Первый вход",
    "sessions_detail_active": "Последняя активность",
    "sessions_current_note": "Текущая сессия (нельзя завершить отсюда)",
    "sessions_btn_revoke": "Завершить сессию",
    "sessions_btn_revoking": "Завершение...",
    "sessions_terminated_note": "Сессия была завершена",
    "sessions_sec_title": "Рекомендации по безопасности",
    "sessions_sec_desc_prefix": "Если вы заметили незнакомое устройство или местоположение, немедленно завершите эту сессию и смените пароль в ",
    "sessions_sec_desc_link": "настройках профиля",
    "sessions_sec_desc_suffix": ". Не забывайте выходить из аккаунта на общедоступных компьютерах.",
    "sessions_toast_revoked": "Сессия успешно завершена.",
    "sessions_toast_ip_copied": "IP-адрес скопирован в буфер обмена!",
    "sessions_toast_revoke_error": "Ошибка при завершении сессии."
  },
  en: {
    "sessions_hero_title": "Active Sessions",
    "sessions_hero_desc": "Manage connected devices, monitor browser logins, and secure your Rednest account",
    "sessions_loading": "Loading active sessions...",
    "sessions_try_again": "Try Again",
    "sessions_empty_title": "No sessions found",
    "sessions_empty_desc": "No device sessions have been recorded for your account yet.",
    "sessions_empty_btn": "Back to Profile",
    "sessions_unknown_device": "Unknown Device",
    "sessions_unknown_os": "Unknown OS",
    "sessions_badge_current": "This device",
    "sessions_badge_active": "Active",
    "sessions_badge_terminated": "Terminated",
    "sessions_detail_location": "Location",
    "sessions_unknown_location": "Unknown location",
    "sessions_detail_ip": "IP Address",
    "sessions_detail_created": "First Signed In",
    "sessions_detail_active": "Last Activity",
    "sessions_current_note": "Current session (cannot be terminated from here)",
    "sessions_btn_revoke": "Terminate Session",
    "sessions_btn_revoking": "Terminating...",
    "sessions_terminated_note": "Session has been terminated",
    "sessions_sec_title": "Security Recommendations",
    "sessions_sec_desc_prefix": "If you see an unfamiliar device or location, terminate that session immediately and consider changing your password in your ",
    "sessions_sec_desc_link": "Profile Settings",
    "sessions_sec_desc_suffix": ". Remember to always sign out when using public or shared computers.",
    "sessions_toast_revoked": "Session terminated successfully.",
    "sessions_toast_ip_copied": "IP address copied to clipboard!",
    "sessions_toast_revoke_error": "Error revoking session."
  },
  az: {
    "sessions_hero_title": "Aktiv sessiyalar",
    "sessions_hero_desc": "Hesabınıza qoşulmuş cihazları idarə edin, girişləri nəzərdən keçirin və təhlükəsizliyi təmin edin",
    "sessions_loading": "Aktiv sessiyalar yüklənir...",
    "sessions_try_again": "Yenidən cəhd edin",
    "sessions_empty_title": "Sessiya tapılmadı",
    "sessions_empty_desc": "Hesabınız üçün hələ heç bir cihaz sessiyası qeydə alınmayıb.",
    "sessions_empty_btn": "Profilə qayıt",
    "sessions_unknown_device": "Naməlum cihaz",
    "sessions_unknown_os": "Naməlum ƏS",
    "sessions_badge_current": "Cari cihaz",
    "sessions_badge_active": "Aktiv",
    "sessions_badge_terminated": "Dayandırılıb",
    "sessions_detail_location": "Məkan",
    "sessions_unknown_location": "Naməlum məkan",
    "sessions_detail_ip": "IP ünvanı",
    "sessions_detail_created": "İlk giriş",
    "sessions_detail_active": "Son aktivlik",
    "sessions_current_note": "Cari sessiya (buradan sonlandırıla bilməz)",
    "sessions_btn_revoke": "Sessiyanı sonlandır",
    "sessions_btn_revoking": "Sonlandırılır...",
    "sessions_terminated_note": "Sessiya dayandırılıb",
    "sessions_sec_title": "Təhlükəsizlik tövsiyələri",
    "sessions_sec_desc_prefix": "Tanış olmayan cihaz və ya məkan görsəniz, həmin sessiyanı dərhal dayandırın və ",
    "sessions_sec_desc_link": "Profil Parametrlərində",
    "sessions_sec_desc_suffix": " şifrənizi yeniləyin. İctimai kompüterlərdən istifadə etdikdə hesabınızdan çıxmağı unutmayın.",
    "sessions_toast_revoked": "Sessiya uğurla dayandırıldı.",
    "sessions_toast_ip_copied": "IP ünvanı kopyalandı!",
    "sessions_toast_revoke_error": "Sessiya dayandırılarkən xəta baş verdi."
  }
};

export const getSessionsTranslation = (lang, dataId) => {
  const dict = translations[lang] || translations.az || translations.ru;
  return dict[dataId] || (translations.en && translations.en[dataId]) || dataId;
};
