export const translations = {
  ru: {
    "widget_buynow_cart": "В корзину",
    "widget_buynow_write_review": "Написать отзыв",
    "widget_fortune_aria": "Колесо фортуны",
    "widget_fortune_tooltip": "Вращайте колесо и получайте подарки!",
    "widget_support_aria": "Чат поддержки",
    "widget_support_tooltip": "Готовы помочь вам с выбором",
    "nav_home": "Главная",
    "nav_menu": "Меню",
    "nav_review": "Отзывы",
    "user_nav_login": "Войти",
    "user_nav_profile": "Профиль",
    "user_nav_promos": "Промокоды",
    "user_nav_admin": "Админ панель",
    "user_nav_pos": "POS терминал",
    "user_nav_logout": "Выйти",
    "modal_logout_title": "Выход из аккаунта",
    "modal_logout_text": "Вы уверены, что хотите выйти из своей учетной записи?",
    "modal_logout_confirm": "Выйти",
    "modal_logout_cancel": "Отмена",
    "modal_delete_cancel": "Отмена",
    "modal_delete_remove": "Удалить",
    "modal_delete_deleting": "Удаление...",
    "modal_security_title": "Проверка безопасности",
    "modal_security_desc": "Введите пароль вашей учетной записи для доступа.",
    "modal_security_desc_profile": "Введите пароль учетной записи для доступа к настройкам профиля.",
    "modal_security_desc_addresses": "Введите пароль учетной записи для доступа к адресам доставки.",
    "modal_security_desc_payments": "Введите пароль учетной записи для доступа к способам оплаты.",
    "modal_security_desc_sessions": "Введите пароль учетной записи для доступа к активным сессиям.",
    "modal_security_desc_orders": "Введите пароль учетной записи для доступа к истории заказов.",
    "modal_security_desc_reviews": "Введите пароль учетной записи для доступа к вашим отзывам.",
    "modal_security_placeholder": "Введите пароль",
    "modal_security_unlock": "Подтвердить",
    "modal_security_unlocking": "Проверка..."
  },
  en: {
    "widget_buynow_cart": "Buy Now",
    "widget_buynow_write_review": "Write a Review",
    "widget_fortune_aria": "Wheel of Fortune",
    "widget_fortune_tooltip": "Spin the wheel for a gift!",
    "widget_support_aria": "Support chat",
    "widget_support_tooltip": "Ready to help you with your choice",
    "nav_home": "Home",
    "nav_menu": "Menu",
    "nav_review": "Review",
    "user_nav_login": "Log In",
    "user_nav_profile": "Profile",
    "user_nav_promos": "Promos",
    "user_nav_admin": "Admin",
    "user_nav_pos": "POS Terminal",
    "user_nav_logout": "Log Out",
    "modal_logout_title": "Log Out",
    "modal_logout_text": "Are you sure you want to log out of your account?",
    "modal_logout_confirm": "Log Out",
    "modal_logout_cancel": "Cancel",
    "modal_delete_cancel": "Cancel",
    "modal_delete_remove": "Remove",
    "modal_delete_deleting": "Deleting...",
    "modal_security_title": "Security Check",
    "modal_security_desc": "Enter your account password to proceed.",
    "modal_security_desc_profile": "Enter your account password to access Profile settings.",
    "modal_security_desc_addresses": "Enter your account password to access Delivery Addresses.",
    "modal_security_desc_payments": "Enter your account password to access Payment Methods.",
    "modal_security_desc_sessions": "Enter your account password to access Active Sessions.",
    "modal_security_desc_orders": "Enter your account password to access Order History.",
    "modal_security_desc_reviews": "Enter your account password to access Your Reviews.",
    "modal_security_placeholder": "Enter your password",
    "modal_security_unlock": "Unlock",
    "modal_security_unlocking": "Verifying..."
  },
  az: {
    "widget_buynow_cart": "İndi al",
    "widget_buynow_write_review": "Rəy yazın",
    "widget_fortune_aria": "Hədiyyə çarxı",
    "widget_fortune_tooltip": "Hədiyyə üçün çarxı fırladın!",
    "widget_support_aria": "Dəstək çatı",
    "widget_support_tooltip": "Seçiminizdə sizə kömək etməyə hazırıq",
    "nav_home": "Ana səhifə",
    "nav_menu": "Menyu",
    "nav_review": "Rəylər",
    "user_nav_login": "Daxil ol",
    "user_nav_profile": "Profil",
    "user_nav_promos": "Promokodlar",
    "user_nav_admin": "Admin",
    "user_nav_pos": "POS terminal",
    "user_nav_logout": "Çıxış",
    "modal_logout_title": "Hesabdan çıxış",
    "modal_logout_text": "Hesabınızdan çıxmaq istədiyinizə əminsiniz?",
    "modal_logout_confirm": "Çıxış",
    "modal_logout_cancel": "Ləğv et",
    "modal_delete_cancel": "Ləğv et",
    "modal_delete_remove": "Sil",
    "modal_delete_deleting": "Silinir...",
    "modal_security_title": "Təhlükəsizlik yoxlaması",
    "modal_security_desc": "Davam etmək üçün hesabınızın şifrəsini daxil edin.",
    "modal_security_desc_profile": "Profil ayarlarına daxil olmaq üçün hesabınızın şifrəsini daxil edin.",
    "modal_security_desc_addresses": "Çatdırılma ünvanlarına daxil olmaq üçün hesabınızın şifrəsini daxil edin.",
    "modal_security_desc_payments": "Ödəniş üsullarına daxil olmaq üçün hesabınızın şifrəsini daxil edin.",
    "modal_security_desc_sessions": "Aktiv sessiyalara daxil olmaq üçün hesabınızın şifrəsini daxil edin.",
    "modal_security_desc_orders": "Sifariş tarixçəsinə daxil olmaq üçün hesabınızın şifrəsini daxil edin.",
    "modal_security_desc_reviews": "Rəylərinizə daxil olmaq üçün hesabınızın şifrəsini daxil edin.",
    "modal_security_placeholder": "Şifrənizi daxil edin",
    "modal_security_unlock": "Təsdiqlə",
    "modal_security_unlocking": "Yoxlanılır..."
  }
};

export const getWidgetTranslation = (lang, dataId) => {
  const dict = translations[lang] || translations.az || translations.ru;
  return dict[dataId] || translations.en[dataId] || dataId;
};

