export const translations = {
  az: {
    title: 'Sifarişlərim',
    subtitle: 'Qəbzlərinizə, sifariş tarixçənizə baxın və statusları canlı izləyin',
    all: 'Hamısı',
    pending: 'Gözləmədə',
    completed: 'Tamamlanıb',
    cancelled: 'Ləğv edilib',
    searchPlaceholder: 'Sifariş ID və ya məhsul üzrə axtarış...',
    loadingOrders: 'Sifarişləriniz yüklənir...',
    loadError: 'Sifarişlərinizi yükləmək mümkün olmadı. Zəhmət olmasa yenidən cəhd edin.',
    tryAgain: 'Yenidən cəhd et',
    noMatching: 'Uyğun sifariş tapılmadı',
    noFilterOrders: '{filter} statusunda sifariş tapılmadı',
    noOrdersYet: 'Hələ heç bir sifariş yoxdur',
    searchHint: 'Başqa açar sözlə axtarmağı və ya axtarışı təmizləməyi yoxlayın.',
    emptyHint: 'Təzə qovrulmuş qəhvə, xüsusi latte və sənətkar desertləri ilə özünüzü sevindirin!',
    browseMenu: 'Menyuya bax',
    copy: 'Kopyala',
    copied: 'Kopyalandı!',
    copyFullId: 'Tam sifariş ID-sini kopyalayın',
    copiedToast: 'Sifariş ID buferə kopyalandı!',
    qty: 'Say',
    totalAmount: 'Ümumi məbləğ:',
    receiptDetails: 'Qəbz detalları',
    orderAgain: 'Yenidən sifariş et',
    adding: 'Əlavə edilir...',
    reorderSuccess: '{count} məhsul səbətə əlavə edildi!',
    reorderError: 'Məhsulları səbətə əlavə etmək mümkün olmadı.',
    saved: 'Qənaət',
    artisanCoffee: 'Xüsusi Qəhvə',
    coffeeItem: 'Qəhvə Məhsulu',
    statusPaidOnline: 'Onlayn ödənilib',
    statusPending: 'Ödəniş gözlənilir',
    statusPreparing: 'Hazırlanır',
    statusReady: 'Götürülməyə hazırdır',
    statusCancelled: 'Ləğv edilib',
    statusCompleted: 'Tamamlanıb',
    payCashDesk: 'Kassa (Nağd)',
    payCardRegister: 'Kassada kartla',
    payWalletBalance: 'Balans hesabı',
    payBankCard: 'Bank kartı',
    payStripe: 'Stripe',
    payGooglePay: 'Google Pay',
    payCashier: 'Kassada ödəniş',
    receiptTitle: 'REDNEST COFFEE',
    receiptSub: 'Xüsusi Qəhvə & Sənətkar Qovurma',
    receiptNumber: 'Qəbz nömrəsi:',
    dateTime: 'Tarix və Saat:',
    itemCol: 'MƏHSUL',
    qtyCol: 'SAY',
    totalCol: 'CƏMİ',
    subtotal: 'Məhsulların cəmi',
    discount: 'Endirim',
    paymentMethod: 'Ödəniş üsulu',
    totalPaid: 'Ödənilmiş yekun məbləğ',
    close: 'Bağla',
    reorderThis: 'Bunu yenidən sifariş et',
  },
  ru: {
    title: 'Мои заказы',
    subtitle: 'Просматривайте чеки, историю заказов и отслеживайте статусы в реальном времени',
    all: 'Все',
    pending: 'В ожидании',
    completed: 'Завершенные',
    cancelled: 'Отмененные',
    searchPlaceholder: 'Поиск по номеру заказа или названию...',
    loadingOrders: 'Загрузка ваших заказов...',
    loadError: 'Не удалось загрузить заказы. Пожалуйста, попробуйте снова.',
    tryAgain: 'Попробовать снова',
    noMatching: 'Заказы не найдены',
    noFilterOrders: 'Заказов со статусом «{filter}» не найдено',
    noOrdersYet: 'Заказов пока нет',
    searchHint: 'Попробуйте изменить поисковый запрос или очистите строку поиска.',
    emptyHint: 'Побалуйте себя свежеобжаренным кофе, фирменными латте и изысканными десертами!',
    browseMenu: 'В меню',
    copy: 'Копировать',
    copied: 'Скопировано!',
    copyFullId: 'Скопировать полный номер заказа',
    copiedToast: 'Номер заказа скопирован в буфер обмена!',
    qty: 'Кол-во',
    totalAmount: 'Итоговая сумма:',
    receiptDetails: 'Детали чека',
    orderAgain: 'Повторить заказ',
    adding: 'Добавление...',
    reorderSuccess: '{count} товар(ов) добавлено в корзину!',
    reorderError: 'Не удалось добавить товары в корзину.',
    saved: 'Экономия',
    artisanCoffee: 'Авторский кофе',
    coffeeItem: 'Позиция кофе',
    statusPaidOnline: 'Оплачено онлайн',
    statusPending: 'Ожидает оплаты',
    statusPreparing: 'Готовится',
    statusReady: 'Готов к выдаче',
    statusCancelled: 'Отменен',
    statusCompleted: 'Завершен',
    payCashDesk: 'Касса (Наличные)',
    payCardRegister: 'Картой на кассе',
    payWalletBalance: 'Баланс кошелька',
    payBankCard: 'Банковская карта',
    payStripe: 'Stripe',
    payGooglePay: 'Google Pay',
    payCashier: 'Оплата на кассе',
    receiptTitle: 'REDNEST COFFEE',
    receiptSub: 'Спешелти кофе & Авторская обжарка',
    receiptNumber: 'Номер чека:',
    dateTime: 'Дата и время:',
    itemCol: 'ТОВАР',
    qtyCol: 'КОЛ-ВО',
    totalCol: 'ИТОГО',
    subtotal: 'Стоимость товаров',
    discount: 'Скидка',
    paymentMethod: 'Способ оплаты',
    totalPaid: 'Итого оплачено',
    close: 'Закрыть',
    reorderThis: 'Повторить этот заказ',
  },
  en: {
    title: 'My Orders',
    subtitle: 'Review your coffee receipts, order history, and track live statuses',
    all: 'All',
    pending: 'Pending',
    completed: 'Completed',
    cancelled: 'Cancelled',
    searchPlaceholder: 'Search by order ID or item...',
    loadingOrders: 'Loading your orders...',
    loadError: 'Could not load your orders. Please try again.',
    tryAgain: 'Try Again',
    noMatching: 'No matching orders found',
    noFilterOrders: 'No {filter} orders found',
    noOrdersYet: 'No orders placed yet',
    searchHint: 'Try searching with a different keyword or clear your search query.',
    emptyHint: 'Treat yourself to freshly roasted coffee, signature lattes, and artisan desserts!',
    browseMenu: 'Browse Menu',
    copy: 'Copy',
    copied: 'Copied!',
    copyFullId: 'Copy full Order ID',
    copiedToast: 'Order ID copied to clipboard!',
    qty: 'Qty',
    totalAmount: 'Total Amount:',
    receiptDetails: 'Receipt Details',
    orderAgain: 'Order Again',
    adding: 'Adding...',
    reorderSuccess: 'Added {count} item(s) to your basket!',
    reorderError: 'Could not add items to basket.',
    saved: 'Saved',
    artisanCoffee: 'Artisan Coffee',
    coffeeItem: 'Coffee Item',
    statusPaidOnline: 'Paid Online',
    statusPending: 'Pending Payment',
    statusPreparing: 'Preparing',
    statusReady: 'Ready for Pickup',
    statusCancelled: 'Cancelled',
    statusCompleted: 'Completed',
    payCashDesk: 'Cash Desk',
    payCardRegister: 'Card at Register',
    payWalletBalance: 'Wallet Balance',
    payBankCard: 'Bank Card',
    payStripe: 'Stripe',
    payGooglePay: 'Google Pay',
    payCashier: 'Pay at Cashier',
    receiptTitle: 'REDNEST COFFEE',
    receiptSub: 'Specialty Coffee & Artisan Roasts',
    receiptNumber: 'Receipt Number:',
    dateTime: 'Date & Time:',
    itemCol: 'ITEM',
    qtyCol: 'QTY',
    totalCol: 'TOTAL',
    subtotal: 'Subtotal',
    discount: 'Discount',
    paymentMethod: 'Payment Method',
    totalPaid: 'Total Amount Paid',
    close: 'Close',
    reorderThis: 'Reorder This',
  },
};

export const getOrdersTranslation = (lang, id) => {
  return translations[lang]?.[id] || translations.az?.[id] || translations.en?.[id] || id;
};
