export const translations = {
  ru: {
    "home_hero_title": "Пробудите ваши чувства",
    "home_hero_subtitle_1": "Оцените богатый, насыщенный вкус наших фирменных кофейных блендов.",
    "home_hero_subtitle_2": "Создано со страстью, подано с безупречностью.",
    "home_hero_btn": "Смотреть меню",
    "home_feature_1_title": "Премиальная обжарка",
    "home_feature_1_desc": "С лучших ферм мира для незабываемого вкуса.",
    "home_feature_2_title": "Уютная атмосфера",
    "home_feature_2_desc": "Идеальное место для отдыха, работы или встреч с друзьями.",
    "home_feature_3_title": "Экологичность",
    "home_feature_3_desc": "Мы заботимся об экологии и используем перерабатываемую упаковку.",
    "home_favorites_title": "Наши любимые",
    "home_favorites_subtitle": "Попробуйте напитки, которые наши гости выбирают чаще всего.",
    "home_favorites_badge": "Любимые",
    "home_favorites_empty": "На данный момент нет доступных товаров.",
    "home_favorites_btn": "Всё меню",
    "home_about_title": "Атмосфера Rednest",
    "home_about_p1": "В Rednest мы верим, что кофе — это не просто напиток, а настоящий ритуал. Мы тщательно отбираем зерна с экологичных ферм по всему миру, чтобы каждая чашка была наполнена страстью и заботой.",
    "home_about_p2": "Наши бариста — настоящие мастера своего дела, вкладывающие душу в каждый латте, капучино и колд брю. Окунитесь в наш уют и откройте новые грани вкуса.",
    "home_club_title": "Вступайте в Rednest Club",
    "home_club_desc": "Подпишитесь, чтобы первыми получать эксклюзивные предложения, новости о свежих обжарках и секреты заваривания прямо на почту.",
    "home_club_placeholder": "Введите ваш email",
    "home_club_btn": "Подписаться",
    "home_club_btn_loading": "Отправка...",
    "home_modal_sub_title": "Подтверждение подписки",
    "home_modal_sub_desc": "Мы отправили 4-значный код на",
    "home_modal_sub_confirm_btn": "Подтвердить",
    "home_modal_sub_resend_btn": "Отправить снова",
    "home_modal_sub_cancel_btn": "Отмена",
    "home_modal_err_title": "Ошибка подписки",
    "home_modal_err_create_acc": "Создать аккаунт",
    "home_modal_err_close": "Закрыть",
    "home_modal_succ_title": "Успешно!",
    "home_modal_succ_btn": "Отлично!"
  },
  en: {
    "home_hero_title": "Awaken Your Senses",
    "home_hero_subtitle_1": "Experience the rich, bold flavors of our premium coffee blends.",
    "home_hero_subtitle_2": "Crafted with passion, served with perfection.",
    "home_hero_btn": "Explore Menu",
    "home_feature_1_title": "Premium Roast",
    "home_feature_1_desc": "Sourced from the finest farms around the globe for an unforgettable taste.",
    "home_feature_2_title": "Cozy Atmosphere",
    "home_feature_2_desc": "A perfect environment to relax, work, or catch up with friends.",
    "home_feature_3_title": "Eco-Friendly",
    "home_feature_3_desc": "Committed to sustainable practices and 100% recyclable packaging.",
    "home_favorites_title": "Our Favorites",
    "home_favorites_subtitle": "Discover the drinks our customers love the most.",
    "home_favorites_badge": "Favorite",
    "home_favorites_empty": "No products currently available.",
    "home_favorites_btn": "View Full Menu",
    "home_about_title": "The Rednest Experience",
    "home_about_p1": "At Rednest, we believe that coffee is more than just a drink—it's a ritual. We meticulously source our beans from sustainable farms across the globe, ensuring every cup you enjoy is crafted with passion and respect for the environment.",
    "home_about_p2": "Our baristas are artisans, dedicated to pouring perfection into every latte, cappuccino, and cold brew. Step into our cozy atmosphere and let us awaken your senses.",
    "home_club_title": "Join the Rednest Club",
    "home_club_desc": "Subscribe to receive exclusive offers, new roast announcements, and brewing tips directly to your inbox.",
    "home_club_placeholder": "Enter your email address",
    "home_club_btn": "Subscribe",
    "home_club_btn_loading": "Sending...",
    "home_modal_sub_title": "Confirm Subscription",
    "home_modal_sub_desc": "We sent a 4-digit code to",
    "home_modal_sub_confirm_btn": "Confirm",
    "home_modal_sub_resend_btn": "Resend Code",
    "home_modal_sub_cancel_btn": "Cancel",
    "home_modal_err_title": "Subscription Error",
    "home_modal_err_create_acc": "Create Account",
    "home_modal_err_close": "Close",
    "home_modal_succ_title": "Success!",
    "home_modal_succ_btn": "Great!"
  },
  az: {
    "home_hero_title": "Hisslərinizi oyadın",
    "home_hero_subtitle_1": "Premium qəhvə çeşidlərimizin zəngin və dolğun dadını kəşf edin.",
    "home_hero_subtitle_2": "Ehtirasla hazırlanmış, mükəmməlliklə təqdim edilmişdir.",
    "home_hero_btn": "Menyuya baxın",
    "home_feature_1_title": "Premium qovurma",
    "home_feature_1_desc": "Unudulmaz dad üçün dünyanın ən yaxşı fermalarından toplanmışdır.",
    "home_feature_2_title": "Rahat atmosfer",
    "home_feature_2_desc": "İstirahət etmək, işləmək və ya dostlarla görüşmək üçün mükəmməl məkan.",
    "home_feature_3_title": "Ekoloji təmiz",
    "home_feature_3_desc": "Davamlı təcrübələrə və 100% təkrar emal olunan qablaşdırmaya sadiqik.",
    "home_favorites_title": "Sevimlilərimiz",
    "home_favorites_subtitle": "Müştərilərimizin ən çox sevdiyi içkiləri kəşf edin.",
    "home_favorites_badge": "Sevimli",
    "home_favorites_empty": "Hazırda heç bir məhsul yoxdur.",
    "home_favorites_btn": "Bütün menyu",
    "home_about_title": "Rednest təcrübəsi",
    "home_about_p1": "Rednest-də biz inanırıq ki, qəhvə sadəcə bir içki deyil — bu, bir ayindir. Hər bir fincandan zövq almağınız üçün dənələri dünyanın ekoloji fermalarından diqqətlə seçirik.",
    "home_about_p2": "Baristalarımız hər bir latte, kapuçino və cold brew-a mükəmməllik qatan sənətkarlardır. Rahat atmosferimizə daxil olun və hisslərinizi oyatmağımıza icazə verin.",
    "home_club_title": "Rednest Klubuna qoşulun",
    "home_club_desc": "Eksklüziv təklifləri, yeni qovurma xəbərlərini və dəmləmə məsləhətlərini birbaşa poçtunuza almaq üçün abunə olun.",
    "home_club_placeholder": "E-poçt ünvanınızı daxil edin",
    "home_club_btn": "Abunə ol",
    "home_club_btn_loading": "Göndərilir...",
    "home_modal_sub_title": "Abunəliyi təsdiqləyin",
    "home_modal_sub_desc": "4 rəqəmli kodu göndərdik:",
    "home_modal_sub_confirm_btn": "Təsdiqlə",
    "home_modal_sub_resend_btn": "Kodu yenidən göndər",
    "home_modal_sub_cancel_btn": "Ləğv et",
    "home_modal_err_title": "Abunəlik xətası",
    "home_modal_err_create_acc": "Hesab yarat",
    "home_modal_err_close": "Bağla",
    "home_modal_succ_title": "Uğurlu!",
    "home_modal_succ_btn": "Əla!"
  }
};

export const getHomeTranslation = (lang, dataId) => {
  const dict = translations[lang] || translations.ru;
  return dict[dataId] || translations.en[dataId] || dataId;
};
